// B.1 · Norwegian sources.
const DIGITAL_IMAGE = '{medium}, {platform} ({url} : accessed {accessed})';
const OSLO = { platform: 'Digitalarkivet', archive: 'Statsarkivet i Oslo' };
const RIKSARKIVET = { platform: 'Digitalarkivet', pubmedium: 'Database with images', archive: 'Riksarkivet' };

const PARISH_SOURCE = [
  ['fylke', 'Fylke / amt', 'Akershus'], ['parish', 'Parish', 'Eidsvoll'], ['vol', 'Volume', 'I 5'],
  ['years', 'Years', '1862–1869'], ['call', 'Call number', 'AV/SAO-A-10888/A/Aa/L0005'],
];
const PAGE = ['page', 'Page', 'blank if unnumbered'];
const IMAGE = ['image', 'Image', 'if not the page, or if unnumbered'];
const PARISH_LOCATORS = [PAGE, IMAGE, ['entry', 'Entry no.']];
const PARISH_NOUNS = ['birth and baptism entry', 'baptism entry', 'death entry', 'burial entry', 'marriage entry'];
const PARISH_PAGE_PIN = ['B.1 §7', 'Parish | p. [P] (image [I]), [entry], [subject]'];
const UNPAGINATED_PIN = ['B.1 §7', 'Unpaginated fallback: when the page has no number, lead with the image number: image [I], [entry], [subject]'];
/** Eidsvoll sorenskriveri → Eidsvoll, for the court's gloss. */
const courtPlace = court => String(court || '').replace(/\s+sorenskriveri$/i, '').trim();

export const NORWEGIAN = [
  {
    id: 'no-ministerialbok', chapter: 'no', group: 'Parish registers (kirkebøker)', name: 'Ministerialbok',
    hint: "The minister's original register",
    source: PARISH_SOURCE, citation: PARISH_LOCATORS, nouns: PARISH_NOUNS,
    defaults: OSLO, confidence: 'Very High', doctype: 'vital record',
    title: 'Norway, {fylke}, {parish}, Ministerialbok [parish register] {vol}, {years}',
    abbrev: '{parish} kirkebok {vol} ({years})',
    author: '{parish} prestekontor',
    page: '{pageLoc}, no. {entry}, {subject}',
    frn: `{parish} prestekontor, Ministerialbok [parish register] no. {vol}, {years}, {pageRef}, no. {entry}, {name}« {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{parish} kirkebok {vol} ({years}), {pageRef}, no. {entry}, {srnSubject}.',
    detailsLabel: 'Entry details (dates, parents, church)',
    pins: {
      title: [['B.1 §4', "Parish, minister's original | Norway, [Fylke/Amt], [Parish], Ministerialbok [parish register] [Roman] [Arabic], [years]"]],
      page: [PARISH_PAGE_PIN, UNPAGINATED_PIN],
      author: [['B.1 §2', 'Parish records | [Parish] prestekontor']],
      abbrev: [['B.1 §10', 'Ministerialbok I 5 | kirkebok I 5']],
      confidence: [['B.1 §8', 'Ministerialbok | Very High for an entry written by the minister within days']],
    },
    examples: [],
  },
  {
    id: 'no-klokkerbok', chapter: 'no', group: 'Parish registers (kirkebøker)', name: 'Klokkerbok',
    hint: "The sacristan's duplicate (parish register copy). Prefer the ministerialbok when you can reach it.",
    source: PARISH_SOURCE, citation: PARISH_LOCATORS, nouns: PARISH_NOUNS,
    defaults: OSLO, confidence: 'High', doctype: 'vital record',
    title: 'Norway, {fylke}, {parish}, Klokkerbok [parish register (copy)] {vol}, {years}',
    abbrev: '{parish} klokkerbok {vol} ({years})',
    author: '{parish} prestekontor',
    page: '{pageLoc}, no. {entry}, {subject}',
    frn: `{parish} prestekontor, Klokkerbok [parish register (copy)] no. {vol}, {years}, {pageRef}, no. {entry}, {name}« {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{parish} klokkerbok {vol} ({years}), {pageRef}, no. {entry}, {srnSubject}.',
    detailsLabel: 'Entry details (dates, parents, church)',
    pins: {
      title: [['B.1 §4', 'Parish, klokkerbok | …, Klokkerbok [parish register (copy)] [Roman] [Arabic], [years]']],
      page: [PARISH_PAGE_PIN, UNPAGINATED_PIN],
      author: [['B.1 §2', 'Parish records | [Parish] prestekontor']],
      abbrev: [['B.1 §10', 'Klokkerbok I 2 | klokkerbok I 2']],
      confidence: [['B.1 §8', 'Klokkerbok | High by default (contemporaneous duplicate)']],
    },
    examples: [{
      guide: 'B.1 Example 1',
      inputs: {
        fylke: 'Akershus', parish: 'Eidsvoll', vol: 'I 2', years: '1866–1871', call: 'AV/SAO-A-10888/G/Ga/L0002',
        page: '57', image: '62', entry: '21', name: 'Thor Emil', noun: 'birth and baptism entry',
        url: 'https://urn.digitalarkivet.no/URN:NBN:no-a1450-kb20060313011115.jpg', accessed: '17 April 2026', eventYear: '1869',
        details: '(born 1 September 1869; baptized 16 January 1870), son of Christian Henningsen and Anne Marthe Bergersdatter, baptized at Eidsvoll church',
      },
    }],
  },
  {
    id: 'no-confirmation', chapter: 'no', group: 'Parish registers (kirkebøker)', name: 'Confirmation or communion',
    hint: "Recorded inside the kirkebok; cite it under that volume's Source.",
    source: [
      ['fylke', 'Fylke / amt', 'Akershus'], ['parish', 'Parish', 'Eidsvoll'],
      ['book', 'Book', 'Ministerialbok or Klokkerbok'], ['vol', 'Volume', 'I 2'],
      ['years', 'Years', '1866–1871'], ['call', 'Call number', 'AV/SAO-A-10888/G/Ga/L0002'],
    ],
    citation: [['section', 'Section', 'confirmations or communicants'], PAGE, IMAGE, ['entry', 'Entry no.']],
    nouns: ['confirmation entry', 'communion entry'],
    defaults: OSLO, confidence: 'High', doctype: 'religious',
    derive: v => {
      const minister = /^minist/i.test(String(v.book || '').trim());
      return {
        kb: minister ? 'kirkebok' : 'klokkerbok',
        bookName: minister ? 'Ministerialbok' : 'Klokkerbok',
        bookGloss: minister ? 'parish register' : 'parish register (copy)',
      };
    },
    title: 'Norway, {fylke}, {parish}, {bookName} [{bookGloss}] {vol}, {years}',
    abbrev: '{parish} {kb} {vol} ({years})',
    author: '{parish} prestekontor',
    page: '{section}, {pageLoc}«, no. {entry}», {subject}',
    frn: `{parish} prestekontor, {bookName} [{bookGloss}] no. {vol}, {years}, {section} section, {pageRef}«, no. {entry}», {name}« {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{parish} {kb} {vol} ({years}), {section}, {pageRef}«, no. {entry}», {srnSubject}.',
    detailsLabel: 'Entry details (parents, church, year)',
    pins: {
      title: [['B.1 §4', "Confirmation and communion have no Title of their own; they use the kirkebok's Title."]],
      page: [
        ['B.1 §7', 'Confirmation Pending review | confirmations, p. [P] (image [I]), no. [N], [Subject] confirmation entry'],
        ['B.1 §7', 'Communion Pending review | communicants, p. [P] (image [I]), [Subject] communion entry'],
        UNPAGINATED_PIN,
      ],
      author: [['B.1 §2', 'Confirmation, communion | [Parish] prestekontor']],
      confidence: [['B.1 §8', 'Confirmation entry Pending review | High for the confirmation']],
    },
    examples: [{
      guide: 'B.1 Example 5',
      inputs: {
        fylke: 'Akershus', parish: 'Eidsvoll', book: 'Klokkerbok', vol: 'I 2', years: '1866–1871',
        call: 'AV/SAO-A-10888/G/Ga/L0002', section: 'confirmations', page: '88', image: '91', entry: '14',
        name: 'Karen Indiana Evensdatter', noun: 'confirmation entry',
        url: 'https://www.digitalarkivet.no/...', accessed: '15 June 2026', eventYear: '1869',
        details: '(daughter of Even Hansen), confirmed at Eidsvoll church 1869',
      },
    }],
  },
  {
    id: 'no-minutes', chapter: 'no', group: 'Parish registers (kirkebøker)', name: 'Parish meeting minutes',
    hint: 'Menighetsmøteprotokoll, a series of its own',
    source: [
      ['fylke', 'Fylke / amt', 'Akershus'], ['parish', 'Parish', 'Eidsvoll'], ['vol', 'Volume', '1'],
      ['years', 'Years', '1870–1895'], ['call', 'Call number'],
    ],
    citation: [PAGE, IMAGE, ['date', 'Meeting date']],
    nouns: ['minute entry'],
    defaults: OSLO, confidence: 'High', doctype: 'religious',
    title: 'Norway, {fylke}, {parish}, Menighetsmøteprotokoll [parish meeting minutes] {vol}, {years}',
    abbrev: '{parish} menighetsmøteprotokoll {vol} ({years})',
    author: '{parish} prestekontor',
    page: '{pageLoc}, {date}, {subject}',
    frn: `{parish} prestekontor, Menighetsmøteprotokoll [parish meeting minutes] no. {vol}, {years}, {pageRef}, {date}, {subject}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{parish} menighetsmøteprotokoll {vol} ({years}), {pageRef}, {srnSubject}.',
    subjectLabel: 'Meeting subject',
    pins: {
      title: [['B.1 §4', 'Meeting minutes | Norway, [Fylke/Amt], [Parish], Menighetsmøteprotokoll [parish meeting minutes] [vol], [years]']],
      page: [['B.1 §7', 'Meeting minutes Pending review | p. [P] (image [I]), [date], [subject] minute entry'], UNPAGINATED_PIN],
      abbrev: [['B.1 §10', 'Menighetsmøteprotokoll 1 Pending review | menighetsmøteprotokoll 1 | Eidsvoll menighetsmøteprotokoll 1 (1870–1895)']],
      confidence: [['B.1 §8', 'Meeting minutes Pending review | High for the recorded act or attendance']],
    },
    examples: [],
  },
  {
    id: 'no-folketelling-1801', chapter: 'no', group: 'Census (folketelling)', name: 'Folketelling 1801',
    hint: 'Nominal census, organized by gård',
    source: [['amt', 'Amt', 'Akershus'], ['prestegjeld', 'Prestegjeld', 'Eidsvoll'], ['ref', 'Reference (if needed)', 'L0009'], ['call', 'Call number']],
    citation: [['gard', 'Gård no.'], ['gardname', 'Gård name'], ['hh', 'Household'], ['person', 'Person']],
    nouns: ['household'],
    defaults: RIKSARKIVET, confidence: 'Very High', doctype: 'enumeration',
    title: 'Norway, {amt}, {prestegjeld}, Folketelling [census] 1801«, {ref}»',
    abbrev: '{prestegjeld} folketelling 1801',
    author: 'Riksarkivet',
    page: 'gård {gard} ({gardname}), household {hh}, person {person}, {subject}',
    frn: `Folketelling [census] 1801, {amt}, {prestegjeld} prestegjeld, gård {gard} ({gardname}), household no. {hh}, person no. {person}, {name}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{prestegjeld} folketelling 1801, gård {gard}, household {hh}, {srnSubject}.',
    pins: {
      title: [['B.1 §4', 'Folketelling 1801 | Norway, [Amt], [Prestegjeld], Folketelling [census] 1801, [reference if needed]']],
      page: [['B.1 §7', 'Folketelling 1801 | gård [N] ([name]), household [N], person [N], [Head] household']],
      author: [['B.1 §2', 'Folketelling | Riksarkivet (preferred)']],
      abbrev: [['B.1 §10', 'Folketelling YYYY | folketelling YYYY']],
      confidence: [['B.1 §8', 'Folketelling 1801 | Very High for residence (enumerator visited each gård); Normal for ages']],
    },
    examples: [],
  },
  {
    id: 'no-folketelling', chapter: 'no', group: 'Census (folketelling)', name: 'Folketelling 1865 and later',
    hint: 'Decennial census, by sokn and district. Use the jurisdiction names the census itself uses.',
    source: [['amt', 'Amt or fylke', 'Akershus'], ['prestegjeld', 'Prestegjeld or herred', 'Eidsvoll'], ['year', 'Census year', '1875'], ['call', 'Call number', 'AV/RA-S-2231/E']],
    citation: [['district', 'District (tellekrets)', '009 Blegstad'], ['page', 'Page'], ['hh', 'Household'], ['person', 'Person']],
    note: [['sokn', 'Sokn (FRN)'], ['turl', 'Transcribed entry URL'], ['citing', 'Citing, after the archive']],
    nouns: ['household'],
    defaults: RIKSARKIVET, confidence: 'High', doctype: 'enumeration', eventDate: 'year',
    title: 'Norway, {amt}, {prestegjeld}, Folketelling [census] {year}',
    abbrev: '{prestegjeld} folketelling {year}',
    author: 'Riksarkivet',
    page: 'district {district}, p. {page}, household {hh}, person {person}, {subject}',
    frn: `Folketelling [census] {year}, {amt} fylke, {prestegjeld} prestegjeld«, {sokn} sokn», district {district}, p. {page}, household no. {hh}, person no. {person}, {name}« ({details})»« (documenting {citedFor})»; ${DIGITAL_IMAGE}«; transcribed entry at {turl}»; citing {archive}«, {citing}»; archive reference {call}.`,
    srn: '{prestegjeld} folketelling {year}, p. {page}, household {hh}, {srnSubject}.',
    detailsLabel: 'Entry details (role, age, household)',
    pins: {
      title: [['B.1 §4', 'Folketelling 1865+ | Norway, [Amt or fylke], [Prestegjeld or herred], Folketelling [census] [year]']],
      page: [['B.1 §7', 'Folketelling 1865+ | district [N] [name], p. [N], household [N], person [N], [Head] household']],
      author: [['B.1 §2', 'Folketelling | Riksarkivet (preferred)']],
      abbrev: [['B.1 §10', 'Folketelling YYYY | folketelling YYYY']],
      confidence: [['B.1 §8', 'Folketelling 1865+ | High for residence and household; Normal for ages and birthplaces']],
    },
    examples: [{
      guide: 'B.1 Example 2',
      inputs: {
        amt: 'Akershus', prestegjeld: 'Eidsvoll', year: '1875', call: 'AV/RA-S-2231/E',
        district: '009 Blegstad', page: '1270', hh: '01', person: '006',
        name: 'Karen Indiana Evensdatter', noun: 'household', says: 'tjenestepige', evidence: 'stated age 14', nonHead: true, head: 'Hansen',
        sokn: 'Eidsvoll', url: 'https://www.digitalarkivet.no/ft20110110330371', accessed: '26 April 2026',
        turl: 'https://www.digitalarkivet.no/pf01052052005225',
        citing: 'Statistisk sentralbyrå, Sosioøkonomiske emner, Folketellinger, boliger og boforhold, E: Folketellinger, source ID 52052',
        details: "tjenestepige, stated age 14, in Jens Hansen's household",
      },
    }],
  },
  {
    id: 'no-tingbok', chapter: 'no', group: 'Court and land', name: 'Tingbok',
    hint: 'District court journal (sorenskriverarkiv)',
    source: [['fylke', 'Fylke / amt', 'Akershus'], ['court', 'Sorenskriveri', 'Eidsvoll sorenskriveri'], ['series', 'Series', 'A I 5'], ['years', 'Years', '1820–1830'], ['call', 'Call number']],
    citation: [['folio', 'Folio'], ['session', 'Date or session']],
    nouns: ['land dispute entry', 'court matter entry'],
    defaults: OSLO, confidence: '', doctype: 'legal',
    derive: v => ({ cs: courtPlace(v.court) }),
    title: 'Norway, {fylke}, {court}, Tingbok [court journal] {series}, {years}',
    abbrev: '{court} tingbok {series} ({years})',
    author: '{court}',
    page: 'folio {folio}, {session}, {subject}',
    frn: `{court} [{cs} district court], Tingbok [court journal] {series}, {years}, fol. {folio}, {session}, {subject}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{court} tingbok {series} ({years}), fol. {folio}, {srnSubject}.',
    subjectLabel: 'Parties or subject',
    pins: {
      title: [['B.1 §4', 'Court (tingbok) | Norway, [Fylke/Amt], [Sorenskriveri], Tingbok [court journal] [series], [years]']],
      page: [['B.1 §7', 'Tingbok | folio [F], [date or session], [parties or subject]']],
      author: [['B.1 §2', 'Court records | The creating body, e.g. Eidsvoll sorenskriveri']],
      abbrev: [['B.1 §10', 'Tingbok A I 5 | tingbok A I 5 | Eidsvoll sorenskriveri tingbok A I 5 (1820–1830)']],
    },
    examples: [],
  },
  {
    id: 'no-skifteprotokoll', chapter: 'no', group: 'Court and land', name: 'Skifteprotokoll',
    hint: 'Probate register; folios for the whole skifte go in the page string',
    source: [['fylke', 'Fylke / amt', 'Akershus'], ['court', 'Sorenskriveri', 'Eidsvoll sorenskriveri'], ['series', 'Series', 'II 3'], ['years', 'Years', '1815–1825'], ['call', 'Call number', 'AV/SAO-A-10063/H/Hb/L0003']],
    citation: [['folio', 'Folio range', '145–148']],
    nouns: ['estate entry'],
    defaults: OSLO, confidence: 'High', doctype: 'legal',
    derive: v => ({ cs: courtPlace(v.court) }),
    title: 'Norway, {fylke}, {court}, Skifteprotokoll [probate register] {series}, {years}',
    abbrev: '{court} skifteprotokoll {series} ({years})',
    author: '{court}',
    page: 'folio {folio}, {subject}',
    frn: `{court} [{cs} district court], Skifteprotokoll [probate register] {series}, {years}, fol. {folio}, estate inventory of {name}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{court} skifteprotokoll {series} ({years}), fol. {folio}, {srnSubject}.',
    subjectLabel: 'Deceased',
    detailsLabel: 'Entry details (farm, death)',
    pins: {
      title: [['B.1 §4', 'Probate | Norway, [Fylke/Amt], [Sorenskriveri], Skifteprotokoll [probate register] [series], [years]']],
      page: [['B.1 §7', 'Skifteprotokoll | folio [F]–[F], [Deceased] estate entry']],
      author: [['B.1 §2', 'Probate | The court that conducted it, usually [District] sorenskriveri']],
      abbrev: [['B.1 §10', 'Skifteprotokoll II 3 | skifteprotokoll II 3 | Eidsvoll sorenskriveri skifteprotokoll II 3 (1815–1825)']],
      confidence: [['B.1 §8', 'Skifteprotokoller | High for the death and primary heirs']],
    },
    examples: [{
      guide: 'B.1 Example 3',
      inputs: {
        fylke: 'Akershus', court: 'Eidsvoll sorenskriveri', series: 'II 3', years: '1815–1825', call: 'AV/SAO-A-10063/H/Hb/L0003',
        folio: '145–148', name: 'Anders Hansen', noun: 'estate entry',
        url: 'https://www.digitalarkivet.no/...', accessed: '9 May 2026', eventYear: '1822',
        details: 'Vinger gård, died 1822',
      },
    }],
  },
  {
    id: 'no-matrikkel', chapter: 'no', group: 'Court and land', name: 'Matrikkel',
    hint: 'Cadastral register; one Source per revision (1665, 1723, 1838, 1886/1904…)',
    source: [
      ['amt', 'Amt or fylke (as written)', 'Akershus amt'], ['prestegjeld', 'Prestegjeld or herred (as written)', 'Eidsvoll prestegjeld'],
      ['year', 'Matrikkel year', '1838'], ['protocol', 'Protocol (if needed)'], ['call', 'Call number'],
    ],
    citation: [['gard', 'Gård no.'], ['gardname', 'Gård name', 'Vinger gård'], ['lnr', 'Løpenummer']],
    nouns: ['matrikkel entry'],
    defaults: RIKSARKIVET, confidence: 'High', doctype: 'legal', eventDate: 'year',
    derive: v => ({
      short: String(v.prestegjeld || '').replace(/\s+(prestegjeld|herred)$/i, '').trim(),
      gardshort: String(v.gardname || '').replace(/\s+gård$/i, '').trim(),
    }),
    title: 'Norway, {amt}, {prestegjeld}, Matrikkel [land register] {year}«, {protocol}»',
    abbrev: '{short} matrikkel {year}',
    author: 'Riksarkivet',
    page: 'gård no. {gard}, {gardname}«, løpenummer {lnr}», {subject}',
    frn: `Matrikkel [land register] {year}, {amt}, {prestegjeld}, gård no. {gard}, {gardname}«, løpenummer {lnr}», listed owner {name}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{short} matrikkel {year}, gård {gard} {gardshort}«, løpenr. {lnr}», {srnSubject}.',
    subjectLabel: 'Owner or topic',
    pins: {
      title: [['B.1 §4', 'Matrikkel | Norway, [Fylke or amt], [Prestegjeld or herred], Matrikkel [land register] [year], [protocol if needed]']],
      page: [['B.1 §7', 'Matrikkel | gård no. [matrikkelnr.], [gård name], [løpenummer if specific], [owner or topic]']],
      author: [['B.1 §2', 'Matrikkel | Riksarkivet for centrally held volumes']],
      abbrev: [['B.1 §10', 'Matrikkel 1838 | matrikkel 1838']],
      confidence: [['B.1 §8', 'Matrikkel | High for the cadastral fact; Low for any genealogical inference']],
    },
    examples: [{
      guide: 'B.1 Example 4',
      inputs: {
        amt: 'Akershus amt', prestegjeld: 'Eidsvoll prestegjeld', year: '1838',
        gard: '234', gardname: 'Vinger gård', lnr: '12', name: 'Anders Hansen', noun: 'matrikkel entry',
        url: 'https://www.digitalarkivet.no/...', accessed: '9 May 2026',
      },
    }],
  },
];
