// B.4 · Published and personal sources.
import { isoDate, lastWord, yearOf } from '../tables.js';

const PRIVATE = { custodian: 'Peter Grund', custplace: 'Duluth, Minnesota' };
const HELD_BY = 'privately held by {custodian}«, {custplace}»';

const pagesLabel = pages => (/[–\-,]/.test(String(pages || '')) ? 'pp.' : 'p.');

export const PUBLISHED = [
  {
    id: 'pp-book', chapter: 'pp', group: 'Published works', name: 'Book or bygdebok',
    hint: 'One Source per book (or multi-volume set cited as a unit)',
    source: [
      ['bookAuthor', 'Author', 'Birger Kirkeby'], ['btitle', 'Title'], ['gloss', 'English gloss (foreign titles)'],
      ['vol', 'Volume / part (as cited)', 'vol. 2, pt. 2'], ['city', 'City', 'Oslo'], ['publisher', 'Publisher'],
      ['year', 'Year'], ['format', 'Format (e-book, audiobook…)'], ['abbr', 'Abbrev', 'Eidsvoll bygdebok 2:2'],
    ],
    citation: [],
    pageVariants: [
      {
        key: 'pages', label: 'Pages',
        citation: [['pages', 'Pages', '432–440']],
        page: '{pl} {pages}«, {subject}»',
        frn: '{author}, {btitle}« [{gloss}]»«, {vol}» ({city}: {publisher}, {year}«. {format}»), {pl} {pages}{frnEnd}',
        srn: '{surname}, {abbr}, {pl} {pages}.',
      },
      {
        key: 'chapter', label: 'Chapter',
        citation: [['chapter', 'Chapter title'], ['pages', 'Pages']],
        page: '{chapter}, {pl} {pages}',
        frn: '{author}, "{chapter}," in {btitle}« [{gloss}]»«, {vol}» ({city}: {publisher}, {year}«. {format}»), {pl} {pages}« (documenting {citedFor})».',
        srn: '{surname}, "{chapter}," {pl} {pages}.',
      },
      {
        key: 'volume', label: 'Multi-volume work',
        citation: [['volume', 'Volume'], ['pages', 'Pages']],
        page: 'vol. {volume}, {pl} {pages}«, {subject}»',
        frn: '{author}, {btitle}« [{gloss}]», vol. {volume} ({city}: {publisher}, {year}«. {format}»), {pl} {pages}{frnEnd}',
        srn: '{surname}, {abbr}, vol. {volume}, {pl} {pages}.',
      },
      {
        key: 'encyclopedia', label: 'Encyclopedia entry',
        citation: [['headword', 'Entry headword']],
        page: '{headword}',
        frn: '{author}, {btitle}« [{gloss}]»«, {vol}» ({city}: {publisher}, {year}«. {format}»), s.v. "{headword}{hwClose}',
        srn: '{surname}, {abbr}, s.v. "{headword}."',
      },
    ],
    nouns: ['entry', ''],
    optionalSubject: true,
    defaults: {}, confidence: 'Normal', doctype: 'publication',
    derive: v => ({
      pl: pagesLabel(v.pages),
      surname: lastWord(v.bookAuthor),
      volCap: String(v.vol || '').trim().replace(/^./, ch => ch.toUpperCase()),
      // The FRN ends on the quoted section, if any, then what it is cited for (A7): , "Vinger gård" (documenting …).
      frnEnd: (v.name ? `, "${v.name}${v.citedFor ? '"' : '."'}` : v.citedFor ? '' : '.') + (v.citedFor ? ` (documenting ${v.citedFor}).` : ''),
      hwClose: v.citedFor ? `" (documenting ${v.citedFor}).` : '."',
    }),
    title: '{btitle}',
    abbrev: '{abbr}',
    author: '{bookAuthor}',
    pubinfo: '«{volCap}. »{city}: {publisher}, {year}.« {format}.»« {pubmedium}, {platform} ({home}).»',
    paperlessTitle: '{name} {abbr} {pl} {pages} ({year})',
    subjectLabel: 'Topic or section',
    pins: {
      title: [['B.4 §4', 'Book | [Title]']],
      page: [
        ['B.4 §7', 'Book | p. [N] or pp. [N]–[N], plus subject if relevant'],
        ['B.4 §7', 'Book chapter | [Chapter title], pp. [N]–[N]'],
        ['B.4 §7', 'Multi-volume work | vol. [N], pp. [N]–[N]'],
        ['B.4 §7', 'Encyclopedia | [entry headword]'],
      ],
      author: [['B.4 §2', "Book, one author | Author's name (Birger Kirkeby)"]],
      abbrev: [['B.4 §10', 'Book | Eidsvoll bygdebok 2:2']],
      pubinfo: [
        ['B.4 §6', 'Print book | [City]: [Publisher], year.'],
        ['B.4 §6', 'E-book / audiobook / CD-DVD | [City]: [Publisher], year. [Format].'],
        ['B.4 §6', 'Online book via a library platform | [City]: [Publisher], year. Digital images, [Platform] (URL).'],
      ],
      confidence: [['B.4 §8', 'Normal | Genealogies citing primary records']],
      plTitle: [['C1', 'Published work (book, periodical) | [Topic] [book identifier] [vol] pp. [range] ([pub. year])']],
    },
    examples: [{
      guide: 'B.4 Published book',
      inputs: {
        bookAuthor: 'Birger Kirkeby', btitle: 'Eidsvoll Bygds Historie: Gardene på vestside av Vorma',
        gloss: 'Eidsvoll Parish History: The Farms on the West Side of the Vorma River', vol: 'vol. 2, pt. 2',
        city: 'Oslo', publisher: 'Eidsvoll Bygdebokkomite', year: '1959', abbr: 'Eidsvoll bygdebok 2:2',
        variant: 'pages', pages: '432–440', name: 'Vinger gård', noun: 'entry',
      },
    }],
  },
  {
    id: 'pp-edited-collection', chapter: 'pp', group: 'Published works', name: 'Edited collection',
    hint: 'A book with chapters by different authors (EE 13.65)',
    source: [
      ['editor', 'Editor(s)', 'Sarah L. Wilkerson Freeman and Beverly Greene Bond'], ['btitle', 'Title', 'Tennessee Women: Their Lives and Times'],
      ['city', 'City', 'Athens'], ['publisher', 'Publisher', 'University of Georgia Press'], ['year', 'Year', '2009'], ['abbr', 'Abbrev', 'Tennessee Women 2009'],
    ],
    citation: [['chapterAuthor', 'Chapter author'], ['chapter', 'Chapter title'], ['pages', 'Pages']],
    nouns: [''],
    optionalSubject: true,
    defaults: {}, confidence: 'Normal', doctype: 'publication',
    derive: v => ({ pl: pagesLabel(v.pages), chapterSurname: lastWord(v.chapterAuthor) }),
    title: '{btitle}',
    abbrev: '{abbr}',
    author: '{editor}, editor',
    pubinfo: '{city}: {publisher}, {year}.« {pubmedium}, {platform} ({home}).»',
    page: '{chapter}, {pl} {pages}«, {subject}»',
    frn: '{chapterAuthor}, "{chapter}," in {btitle}, ed. {editor} ({city}: {publisher}, {year}), {pl} {pages}« (documenting {citedFor})».',
    srn: '{chapterSurname}, "{chapter}," {pl} {pages}.',
    subjectLabel: 'Topic (optional)',
    pins: {
      title: [['B.4 §4', 'Edited collection | [Title]']],
      page: [['B.4 §7', 'Book chapter | [Chapter title], pp. [N]–[N]']],
      author: [['B.4 §2', 'Edited collection | [Name], editor (EE 13.65)']],
      abbrev: [['B.4 §10', 'Book | Eidsvoll bygdebok 2:2 · Tennessee Women 2009']],
    },
    examples: [],
  },
  {
    id: 'pp-periodical', chapter: 'pp', group: 'Published works', name: 'Periodical article',
    hint: 'One Source per periodical title; the issue goes in the page string',
    source: [['periodical', 'Periodical', 'American Genealogist'], ['pcity', 'City, state', 'New Haven, Connecticut']],
    citation: [['aauthor', 'Article author'], ['atitle', 'Article title'], ['volume', 'Volume'], ['issue', 'Issue no.'], ['ayear', 'Year'], ['pages', 'Pages']],
    nouns: [''],
    optionalSubject: true,
    defaults: {}, confidence: 'Normal', doctype: 'publication',
    derive: v => ({ pl: pagesLabel(v.pages), articleSurname: lastWord(v.aauthor) }),
    title: '{periodical}, {pcity}',
    abbrev: '{periodical}',
    author: '',
    pubinfo: '{pcity}.',
    page: 'vol. {volume}, no. {issue} ({ayear}), {pl} {pages}«, {subject}»',
    frn: '{aauthor}, "{atitle}," {periodical} {volume} ({ayear}): {pages}« (documenting {citedFor})».',
    srn: '{articleSurname}, "{atitle}," {pages}.',
    subjectLabel: 'Topic (optional)',
    pins: {
      title: [['B.4 §4', 'Periodical | [Title], [city, state]']],
      page: [['B.4 §7', 'Periodical article | vol. [N], no. [N] ([year]), pp. [N]–[N]']],
      author: [['B.4 §2', 'Periodical | Blank']],
      pubinfo: [['B.4 §6', 'Periodical | [City], [State if needed], [Publisher].']],
      abbrev: [['B.4 §10', 'Periodical | American Genealogist']],
    },
    examples: [],
  },
  {
    id: 'pp-register', chapter: 'pp', group: 'Published works', name: 'Directory or register',
    hint: 'Membership roster or school register; one Source per annual issue or volume',
    source: [
      ['issuer', 'Issuing body or compiler', 'Den norske sakførerforening'], ['rtitle', 'Title'], ['gloss', 'English gloss'],
      ['city', 'City', 'Oslo'], ['publisher', 'Publisher'], ['year', 'Year'], ['abbr', 'Abbrev'],
      ['srnAuthor', 'Author in SRN (surname, if a person)', 'Langangen'],
    ],
    citation: [['page', 'Page'], ['image', 'Image', 'if not the page'], ['entry', 'Entry no. (if any)']],
    nouns: ['directory entry', 'register entry'],
    defaults: { platform: 'Nasjonalbiblioteket' }, confidence: 'Normal', doctype: 'publication',
    derive: v => ({ entryLead: String(v.entry || '').trim() ? `entry no. ${String(v.entry).trim()}, ` : 'entry for ' }),
    title: '{rtitle}',
    abbrev: '{abbr}',
    author: '{issuer}',
    pubinfo: '{city}: {publisher}, {year}.« {pubmedium}, {platform} ({home}).»',
    page: 'p. {page}« (image {image})»«, entry no. {entry}», {subject}',
    frn: '{author}, {rtitle}« [{gloss}]» ({city}: {publisher}, {year}), p. {page}, {entryLead}{name}« (documenting {citedFor})»«; {medium}, {platform} ({url} : accessed {accessed})».',
    srn: '«{srnAuthor}, »{abbr}, p. {page}«, no. {entry}», {name}.',
    pins: {
      title: [['B.4 §4', 'Membership directory | [Title with year]'], ['B.4 §4', 'School roster | [Title with years]']],
      page: [['B.4 §7', 'Directory or register | p. [P] (image [I]), entry no. [N], [Name] directory entry (or register entry)']],
      author: [['B.4 §2', 'Membership directory / organizational publication | Issuing body (Den norske sakførerforening)']],
      pubinfo: [['B.4 §6', 'Membership directory | [City]: [Issuing organization], year.']],
      abbrev: [['B.4 §10', 'Register | Sakførerforening medlemmer 1950 · Kristiania katedralskole 1891–1901']],
      confidence: [['B.4 §8', 'Normal | Genealogies citing primary records; biographical and membership directories; school records']],
    },
    examples: [
      {
        guide: 'B.4 Membership directory',
        inputs: {
          issuer: 'Den norske sakførerforening', rtitle: 'Medlemmer av Den norske sakførerforening 1. juli 1950',
          gloss: 'Members of the Norwegian Bar Association as of 1 July 1950', city: 'Oslo', publisher: 'Den norske sakførerforening',
          year: '1951', abbr: 'Sakførerforening medlemmer 1950', page: '440', image: '443', name: 'Frithjof Siggerud', noun: 'directory entry',
          url: 'https://www.nb.no/items/b3f9413b2125c7f26063abb8896d95bf?page=443', accessed: '26 April 2026', eventYear: '1950',
        },
      },
      {
        guide: 'B.4 School enrollment register',
        inputs: {
          issuer: 'Anders Langangen', rtitle: 'Elever ved Kristiania katedralskole som begynte på skolen i årene 1891–1901, hefte 8',
          gloss: 'Pupils at Kristiania Cathedral School Who Began in the Years 1891–1901, Booklet 8', city: '[Place]', publisher: '[Publisher]',
          year: '[year]', abbr: 'Kristiania katedralskole 1891–1901', srnAuthor: 'Langangen',
          page: '112', image: '111', entry: '498', name: 'Erling Frithjof Siggerud', noun: 'register entry',
          url: 'https://www.nb.no', accessed: '26 April 2026',
        },
      },
    ],
  },
  {
    id: 'pp-video', chapter: 'pp', group: 'Published works', name: 'Online video',
    hint: 'Use video only for context, never as the source for a date, name, or relationship',
    source: [
      ['channel', 'Channel or producer', 'Värmland Local History Channel'], ['vtitle', 'Video title'],
      ['vshort', 'Short title (Abbrev)'], ['channelShort', 'Channel in SRN (if shorter)'], ['year', 'Year'],
    ],
    citation: [['range', 'Minute range', '12:30–14:15']],
    nouns: [''],
    defaults: { platform: 'YouTube' }, confidence: 'Low', doctype: 'publication',
    derive: v => ({ topic: String(v.details || '').trim() || v.name, srnChannel: String(v.channelShort || '').trim() || v.channel }),
    title: '{vtitle}',
    abbrev: '{vshort}',
    author: '{channel}',
    pubinfo: 'Online video, {platform} ({home}), {year}.',
    page: 'minute {range}, {subject}',
    frn: '{channel}, "{vtitle}," {platform} video ({url} : accessed {accessed}), minute {range}, on {topic}« (documenting {citedFor})».',
    srn: '{srnChannel}, "{vshort}," minute {range}.',
    subjectLabel: 'Topic',
    detailsLabel: 'Topic as worded in the FRN (if different)',
    paperlessTitle: '{vshort} video clip {year}',
    pins: {
      title: [['B.4 §4', 'Online video | [Title]']],
      page: [['B.4 §7', 'Audio interview / video | minute [N]:[NN], [topic] (or transcript p. [N], [topic])']],
      author: [['B.4 §2', 'Online video | Channel or production company']],
      pubinfo: [['B.4 §6', 'Online video | Online video, [Platform] (homepage URL), year.'], ['A10', 'Online video | Online video, [Platform] (URL), year.']],
      abbrev: [['B.4 §10', 'Online video | Norra Ny walking tour (the SRN may lead with the channel)']],
      plTitle: [['C1', 'Online video | [Short title] video clip [year]']],
    },
    examples: [{
      guide: 'B.4 Online video',
      inputs: {
        channel: 'Värmland Local History Channel', vtitle: 'Norra Ny parish history walking tour', vshort: 'Norra Ny walking tour',
        channelShort: 'Värmland History YouTube', year: '2025', range: '12:30–14:15', name: 'Ambjörby torpare landscape', noun: '',
        details: 'the Ambjörby torpare landscape', url: 'https://www.youtube.com/watch?v=[ID]', accessed: '9 May 2026',
      },
    }],
  },
  {
    id: 'pp-bible', chapter: 'pp', group: 'Family artifacts', name: 'Family Bible',
    hint: 'Photograph the cover, title page, and all family pages before judging confidence',
    source: [
      ['surname', 'Family surname', 'Grund'], ['years', 'Years of entries', '1848–1932'], ['compiler', 'Inferred compiler', 'Per Larsson Grund'],
      ['btitle', 'Bible title', 'The Holy Bible Containing the Old and New Testaments'], ['city', 'Place of publication'],
      ['publisher', 'Bible publisher'], ['year', 'Bible year'],
    ],
    citation: [['pagelabel', 'Page', 'family page 2']],
    nouns: ['birth entry', 'marriage entry', 'death entry'],
    defaults: PRIVATE, confidence: 'High', doctype: 'artifact',
    title: '{surname} Family Bible Records, {years}',
    abbrev: '{surname} Family Bible',
    author: '[{compiler}]',
    pubinfo: '',
    page: '{pagelabel}, {subject}',
    frn: `[{compiler}], compiler, {surname} Family Bible Records, {years}, in {btitle} ({city}: {publisher}, {year}), {pagelabel}, entry for {name}« {details}»« (documenting {citedFor})»; ${HELD_BY}.`,
    srn: '{surname} Family Bible, {pagelabel}, {subject}.',
    detailsLabel: 'Entry details (dates, places)',
    pins: {
      title: [['B.4 §4', 'Family Bible | [Surname] Family Bible Records, [years]']],
      page: [['B.4 §7', 'Family Bible | [record-type] page, [event] (family page, Per Larsson Grund birth entry)']],
      author: [['B.4 §2', 'Family Bible | Inferred compiler in brackets ([Per Larsson Grund]), or blank.']],
      pubinfo: [['B.4 §6', 'Family Bible | Blank']],
      abbrev: [['B.4 §10', 'Family Bible | Grund Family Bible']],
    },
    examples: [{
      guide: 'B.4 Family Bible',
      inputs: {
        surname: 'Grund', years: '1848–1932', compiler: 'Per Larsson Grund', btitle: 'The Holy Bible Containing the Old and New Testaments',
        city: 'Stockholm', publisher: '[Bible publisher]', year: '[year]', pagelabel: 'family page 2',
        name: 'Per Larsson Grund', noun: 'birth entry', details: 'born 14 January 1848 at Ambjörby, Norra Ny parish',
        comment: "Entries appear in two distinct hands: an early hand for events 1848–1880, a later hand for events 1881–1932. The earliest entries appear to have been copied into this Bible from an earlier family record after the Bible's purchase.",
      },
    }],
  },
  {
    id: 'pp-family-record', chapter: 'pp', group: 'Family artifacts', name: 'Family record',
    hint: 'A family record other than a Bible (notes, registers, histories)',
    source: [['family', 'Family or compiler', 'Grund'], ['rtype', 'Record type', 'Family Record'], ['compiler', 'Compiler (if known)']],
    citation: [['pagelabel', 'Page or section']],
    nouns: ['birth entry', 'marriage entry', 'death entry', ''],
    defaults: PRIVATE, confidence: '', doctype: 'artifact',
    title: '{family} {rtype}',
    abbrev: '{family} {rtype}',
    author: '«[{compiler}]»',
    page: '{pagelabel}, {subject}',
    frn: `«[{compiler}], compiler, »{family} {rtype}, {pagelabel}, entry for {name}« {details}»« (documenting {citedFor})»; ${HELD_BY}.`,
    srn: '{family} {rtype}, {pagelabel}, {subject}.',
    pins: {
      title: [['B.4 §4', 'Family record | [Family/compiler] [record type]']],
      author: [['B.4 §2', 'Family record (non-Bible) | Blank, or compiler in brackets']],
    },
    examples: [],
  },
  {
    id: 'pp-funeral-program', chapter: 'pp', group: 'Family artifacts', name: 'Funeral program',
    hint: 'One Source per program unless several artifacts share one provenance (A1)',
    source: [
      ['dname', 'Deceased', 'Thomas Emil Siggerud'], ['funeralHome', 'Funeral home', 'Helgeson Funeral Home'], ['fcity', 'Funeral home city', 'Williams, Minnesota'],
      ['date', 'Service date', '16 February 1953'], ['ptitle', 'Printed title', 'In Memory of Thomas Emil Siggerud'],
    ],
    citation: [],
    nouns: ['funeral program', 'obituary'],
    defaults: PRIVATE, confidence: 'High', doctype: 'ephemera',
    derive: v => ({ surname: lastWord(v.dname), year: yearOf(v.date) }),
    title: 'Funeral program, {dname}',
    abbrev: '{surname} funeral program {year}',
    author: '{funeralHome}',
    pubinfo: '{fcity}: {funeralHome}, {date}.',
    page: '{subject}',
    frn: `{funeralHome}, "{ptitle}," funeral program for services held {date}« {details}»« (documenting {citedFor})»; ${HELD_BY}.`,
    srn: '{surname} funeral program {year}.',
    detailsLabel: 'Service details (church, officiant, burial)',
    paperlessTitle: '{dname} funeral program {year}',
    pins: {
      title: [['B.4 §4', 'Funeral program | Funeral program, [Subject]']],
      page: [['B.4 §7', 'Funeral program | [subject] (short enough to need no page)']],
      author: [['B.4 §2', 'Funeral program | Funeral home (Helgeson Funeral Home)']],
      pubinfo: [['B.4 §6', 'Funeral program | [City]: [Funeral home], date.'], ['A10', 'Funeral program | [City]: [Funeral home], date.']],
      abbrev: [['B.4 §10', 'Artifact | Siggerud funeral program 1953']],
      plTitle: [['C1', 'Funeral program | [Deceased] funeral program [year]']],
    },
    examples: [{
      guide: 'B.4 Funeral program',
      inputs: {
        dname: 'Thomas Emil Siggerud', funeralHome: 'Helgeson Funeral Home', fcity: 'Williams, Minnesota', date: '16 February 1953',
        ptitle: 'In Memory of Thomas Emil Siggerud', name: 'Thomas Emil Siggerud', noun: 'funeral program',
        details: 'at Lutheran Church, Williams, Minnesota; Rev. Edstrom officiating; burial at Pine Hill Cemetery, Williams, Minnesota',
      },
    }],
  },
  {
    id: 'pp-photograph', chapter: 'pp', group: 'Family artifacts', name: 'Photograph',
    hint: 'When the photo itself is the evidence; otherwise attach it to the relevant citation',
    source: [
      ['pname', 'Subject', 'Per Larsson Grund'], ['ptype', 'Photo type', 'cabinet card'], ['pdate', 'Date', 'ca. 1890s'],
      ['photographer', 'Photographer (Author, if known)'], ['studio', 'Studio'], ['scity', 'Studio city'],
    ],
    citation: [['element', 'Image element', 'cabinet card front'], ['element2', 'Second element (optional)']],
    nouns: ['portrait', ''],
    defaults: PRIVATE, confidence: 'High', doctype: 'artifact',
    derive: v => ({ surname: lastWord(v.pname), decade: String(v.pdate || '').replace(/^ca\.\s*/, '').trim() }),
    title: '{pname} {ptype}, {pdate}',
    abbrev: '{surname} {ptype} {decade}',
    author: '«{photographer}»',
    pubinfo: '«{studio}, {scity}, {pdate}.»« {pubmedium}, {platform} ({home}).»',
    page: '{element}, {subject}«; {element2}»',
    frn: `{pname} {ptype} portrait, {pdate}«, taken at {studio}, {scity}»«; {details}»« (documenting {citedFor})»; ${HELD_BY}.`,
    srn: '{pname} {ptype}, {pdate}.',
    detailsLabel: 'Inscriptions and marks (FRN)',
    paperlessTitle: '{pname} photograph {decade}',
    pins: {
      title: [['B.4 §4', 'Photograph | [Subject] [photo type], [year or range]']],
      page: [['B.4 §7', 'Photograph | [image element], [subject], then ; [second element] if needed (cabinet card front, Per Larsson Grund portrait; inscription on mount, "Grandma\'s Grandpa")']],
      author: [['B.4 §2', 'Photograph | Photographer or studio if known']],
      pubinfo: [['B.4 §6', 'Photograph from a studio | [Studio], [city], [year or circa]. if known']],
      abbrev: [['B.4 §10', 'Artifact | Siggerud funeral program 1953 · Grund cabinet card 1890s']],
      plTitle: [['C1', 'Photograph | [Subject] photograph [decade or year]']],
    },
    examples: [{
      guide: 'B.4 Photograph',
      inputs: {
        pname: 'Per Larsson Grund', ptype: 'cabinet card', pdate: 'ca. 1890s', studio: 'Miller Studio', scity: 'St. Cloud, Minnesota',
        element: 'cabinet card front', element2: 'inscription on mount, "Grandma\'s Grandpa"', name: 'Per Larsson Grund', noun: 'portrait',
        details: 'inscription on top of mount in cursive: "Grandma\'s Grandpa"; printed studio mark on bottom of mount: "Miller" (with M-M monogram), "ST. CLOUD, MINN."',
        comment: 'Subject identification is family attribution by inscription rather than caption with full name.',
      },
    }],
  },
  {
    id: 'pp-letter', chapter: 'pp', group: 'Family artifacts', name: 'Family letter',
    hint: 'One letter cited substantively; one collection when the collection is cited',
    source: [['sender', 'Writer', 'Per Larsson Grund'], ['recipient', 'Recipient', 'John Edwin Grund'], ['date', 'Date', '14 March 1925']],
    citation: [],
    nouns: [''],
    defaults: PRIVATE, confidence: 'High', doctype: 'correspondence',
    derive: v => ({ senderSurname: lastWord(v.sender), recipientSurname: lastWord(v.recipient), iso: isoDate(v.date) }),
    title: '{sender} to {recipient}, {date}, letter',
    abbrev: '{senderSurname} to {recipientSurname} letter {iso}',
    author: '{sender}',
    pubinfo: '',
    page: '{subject}',
    frn: `{sender} to {recipient}, letter, {date}«, {details}»« (documenting {citedFor})»; ${HELD_BY}.`,
    srn: '{sender} to {recipient}, {date}.',
    subjectLabel: 'Topic, subject (e.g. report of a death, Name)',
    detailsLabel: 'Content for the FRN',
    paperlessTitle: '{sender} to {recipient} letter {iso}',
    pins: {
      title: [['B.4 §4', 'Letter | [Sender] to [Recipient], [date], letter']],
      author: [['B.4 §2', 'Letter | Writer']],
      pubinfo: [['B.4 §6', 'Letter | Blank']],
      plTitle: [['C1', 'Family letter | [Sender] to [Recipient] letter [YYYY-MM-DD]']],
    },
    examples: [],
  },
  {
    id: 'pp-interview', chapter: 'pp', group: 'People', name: 'Audio interview',
    hint: "The interviewee is the Author (EE 4.31). Never publish a living informant's address (A12).",
    source: [['interviewee', 'Interviewee', 'Tom Grund'], ['interviewer', 'Interviewer', 'Peter Grund'], ['city', 'Place', 'Duluth, Minnesota'], ['date', 'Date', '12 March 2024']],
    citation: [['minute', 'Timestamp', '23:15']],
    nouns: [''],
    defaults: PRIVATE, confidence: 'Normal', doctype: 'interview',
    derive: v => ({ iso: isoDate(v.date), topic: String(v.details || '').trim() || v.name }),
    title: '{interviewee} interview by {interviewer}, {date}',
    abbrev: '{interviewee} interview {iso}',
    author: '{interviewee}',
    pubinfo: 'Recorded interview, {city}, {date}.',
    page: 'minute {minute}, {subject}',
    frn: '{interviewee} ({city}), recorded interview by {interviewer}, {date}; audio recording and transcript privately held by {custodian}, [ADDRESS FOR PRIVATE USE,] {custplace}; minute {minute}, on {topic}« (documenting {citedFor})».',
    srn: '{interviewee} interview, {date}, minute {minute}.',
    subjectLabel: 'Topic',
    detailsLabel: 'Topic as worded in the FRN (if different)',
    paperlessTitle: '{interviewee} interview {iso}',
    pins: {
      title: [['B.4 §4', 'Audio interview | [Interviewee] interview by [Interviewer], [date]']],
      page: [['B.4 §7', 'Audio interview / video | minute [N]:[NN], [topic] (or transcript p. [N], [topic])']],
      author: [['B.4 §2', 'Audio interview | The interviewee (EE 4.31)']],
      pubinfo: [['B.4 §6', 'Audio interview | Recorded interview, [city], date.'], ['A10', 'Audio interview | Recorded interview, [city], date.']],
      abbrev: [['B.4 §10', 'Interview | Tom Grund interview 2024-03-12']],
      plTitle: [['C1', 'Audio interview | [Interviewee] interview [YYYY-MM-DD]']],
    },
    examples: [{
      guide: 'B.4 Audio interview',
      inputs: {
        interviewee: 'Tom Grund', interviewer: 'Peter Grund', city: 'Duluth, Minnesota', date: '12 March 2024',
        minute: '23:15', name: "Edmund Gene Grund's military service in WWII", noun: '', details: "Edmund Gene Grund's WWII service",
        comment: 'Tom is a son of Edmund Gene Grund and reports here on events he learned of from his parents (he was born after the war).',
      },
    }],
  },
  {
    id: 'pp-oral-history', chapter: 'pp', group: 'People', name: 'Oral-history collection',
    hint: 'A collection of interviews cited as a whole',
    source: [['collection', 'Collection title', 'Cane River Oral History Collection'], ['call', 'Call number']],
    citation: [['interviewee', 'Interviewee'], ['interviewer', 'Interviewer'], ['date', 'Interview date'], ['locator', 'Minute or transcript page', 'minute 12:30']],
    nouns: [''],
    defaults: {}, confidence: '', doctype: 'interview',
    derive: v => ({ topic: String(v.details || '').trim() || v.name }),
    title: '{collection}',
    abbrev: '{collection}',
    author: '{collection}',
    page: '{locator}, {subject}',
    frn: '{interviewee}, interview by {interviewer}, {date}, {collection}; {locator}, on {topic}« (documenting {citedFor})»; citing {archive}«, {call}».',
    srn: '{collection}, {interviewee}, {locator}.',
    subjectLabel: 'Topic',
    detailsLabel: 'Topic as worded in the FRN (if different)',
    pins: {
      title: [['B.4 §4', 'Oral-history collection | [Collection title]']],
      page: [['B.4 §7', 'Audio interview / video | minute [N]:[NN], [topic] (or transcript p. [N], [topic])']],
      author: [['B.4 §2', 'Oral-history collection | Collection name']],
    },
    examples: [],
  },
  {
    id: 'pp-research', chapter: 'pp', group: 'People', name: "Another genealogist's research",
    hint: "Their conclusion isn't evidence; their cited sources are. Prefer the primary record.",
    source: [
      ['researcher', 'Researcher', 'Siw Alfreddson'], ['topic', 'Topic (Title)', 'Ambjörby, Sweden'],
      ['rtopic', 'Topic (FRN)', 'the Grund family of Ambjörby, Sweden'], ['years', 'Years', '2024–2026'],
    ],
    citation: [['section', 'Section or item', 'Ambmyra typed page, received 30 April 2026']],
    note: [['copies', 'Copies held by (FRN)', 'Peter Grund, Duluth, Minnesota']],
    nouns: [''],
    optionalSubject: true,
    defaults: { custodian: 'Siw Alfreddson', custplace: 'Ambjörby, Sweden' },
    confidence: 'Normal', doctype: 'research',
    derive: v => ({ surname: lastWord(v.researcher), topicShort: String(v.topic || '').split(',')[0].trim() }),
    title: 'Personal research of {researcher}, {topic}',
    abbrev: '{surname} research',
    author: '{researcher}',
    pubinfo: 'Unpublished research, {custplace}, {years}.',
    page: '{section}«, {subject}»',
    frn: `{researcher}, personal research on {rtopic}, accumulated {years}, {details}« (documenting {citedFor})»; ${HELD_BY}«, with copies privately held by {copies}».`,
    srn: '{surname} research, {section}.',
    subjectLabel: 'Topic, subject (optional)',
    detailsLabel: 'Item description (FRN)',
    eventYearLabel: 'Received (Paperless)',
    paperlessTitle: '{surname} {topicShort} research {eventYear}',
    pins: {
      title: [['B.4 §4', 'Personal research | Personal research of [Researcher], [topic]']],
      page: [['B.4 §7', 'Personal research | [topic or section], [page if compiled]']],
      author: [['B.4 §2', 'Personal research | Researcher (Siw Alfreddson)']],
      pubinfo: [['B.4 §6', 'Personal research | Unpublished research, [location], [year-range].'], ['A10', 'Personal research | Unpublished research, [location], [year-range].']],
      abbrev: [['B.4 §10', 'Personal research | Alfreddson research']],
      plTitle: [['C1', 'Personal research | [Researcher surname] [topic] research [YYYY-MM-DD, YYYY, or range]']],
    },
    examples: [{
      guide: 'B.4 Personal research',
      inputs: {
        researcher: 'Siw Alfreddson', topic: 'Ambjörby, Sweden', rtopic: 'the Grund family of Ambjörby, Sweden',
        years: '2024–2026', section: 'Ambmyra typed page, received 30 April 2026',
        details: 'typed page on Ambmyra torpare holdings, received by Peter Grund via email 30 April 2026',
        copies: 'Peter Grund, Duluth, Minnesota', eventYear: '2026-04-30',
        comment: "Siw's notes cite Norra Ny kyrkoarkiv volumes for each fact she records; for facts she draws from those primary records, the underlying primary record should also be cited directly when used in narrative.",
      },
    }],
  },
];
