// B.2 · Swedish sources.
import { gap } from '../template.js';
const DIGITAL_IMAGE = '{medium}, {platform} ({url} : accessed {accessed})';
const VARMLAND_RA = { platform: 'Riksarkivet', archive: 'Värmlandsarkiv' };
const VARMLAND_AD = { platform: 'ArkivDigital', archive: 'Värmlandsarkiv' };

const PARISH_SOURCE = [
  ['lan', 'Län', 'Värmland'], ['parish', 'Parish', 'Norra Ny'], ['vol', 'Volume', 'AI:11'],
  ['years', 'Years', '1812–1820'], ['call', 'Call number', 'SE/VA/13398/A I/11'],
];
const PAGE_IMAGE = [['page', 'Page', 'blank if unnumbered'], ['image', 'Image', 'if not the page, or if unnumbered']];
const PAGE_IMAGE_ENTRY = [...PAGE_IMAGE, ['entry', 'Entry no.']];
const PARISH_AUTHOR_PIN = ['B.2 §2', 'Parish records, incl. confirmation, communion, minutes | [Parish] församling'];
const UNPAGINATED_PIN = ['B.2 §7', 'Unpaginated fallback is image [I], [entry], [subject]'];

/** Värmland → Värmlands län (Swedish genitive). */
const lanFull = lan => {
  const l = String(lan || '').trim();
  return l ? `${l.endsWith('s') ? l : l + 's'} län` : '';
};

export const SWEDISH = [
  {
    id: 'se-husforhor', chapter: 'se', group: 'Parish records (kyrkoarkiv)', name: 'Husförhörslängd',
    hint: 'Clerical survey (household examination); one Source per volume',
    source: PARISH_SOURCE, citation: PAGE_IMAGE, nouns: ['household', 'household examination entry'],
    defaults: VARMLAND_RA, confidence: 'High', doctype: 'enumeration',
    title: 'Sweden, {lan}, {parish}, Husförhörslängder [household examinations] {vol}, {years}',
    abbrev: '{parish} husförhörslängd {vol} ({years})',
    author: '{parish} församling',
    page: '{pageLoc}, {subject}',
    frn: `{parish} församling, Husförhörslängder [household examinations], vol. {vol} ({years}), {pageRef}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{parish} husförhörslängd {vol} ({years}), {pageRef}, {srnSubject}.',
    pins: {
      title: [['B.2 §4', 'Clerical survey | Sweden, [län], [parish], Husförhörslängder [household examinations] [vol], [years]']],
      page: [['B.2 §7', 'Husförhörslängd household | p. [P] (image [I]), [Head] household'], UNPAGINATED_PIN],
      author: [PARISH_AUTHOR_PIN],
      abbrev: [['B.2 §10', 'Husförhörslängder | husförhörslängd']],
      confidence: [['B.2 §8', 'Husförhörslängd household | High residence; Normal stated age']],
    },
    examples: [{
      guide: 'B.2 Example 1',
      inputs: {
        lan: 'Värmland', parish: 'Norra Ny', vol: 'AI:11', years: '1812–1820', call: 'SE/VA/13398/A I/11',
        page: '8', image: '19', name: 'Per Persson', noun: 'household',
        url: 'https://sok.riksarkivet.se/bildvisning/C0038409_00019', accessed: '20 April 2026', eventYear: '1812–1820',
        details: 'Ambjörby Torpare',
      },
    }],
  },
  {
    id: 'se-dopbok', chapter: 'se', group: 'Parish records (kyrkoarkiv)', name: 'Födelse- och dopbok',
    hint: 'Birth and baptism book',
    source: PARISH_SOURCE, citation: PAGE_IMAGE_ENTRY, nouns: ['birth and baptism entry', 'birth entry', 'baptism entry'],
    defaults: VARMLAND_AD, confidence: 'Very High', doctype: 'vital record',
    title: 'Sweden, {lan}, {parish}, Födelse- och dopböcker [birth and baptism books] {vol}, {years}',
    abbrev: '{parish} dopbok {vol} ({years})',
    author: '{parish} församling',
    page: '{pageLoc}, no. {entry}, {subject}',
    frn: `{parish} församling, Födelse- och dopböcker [birth and baptism books], vol. {vol} ({years}), {pageRef}, no. {entry}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{parish} dopbok {vol} ({years}), {pageRef}, no. {entry}, {srnSubject}.',
    pins: {
      title: [['B.2 §4', 'Birth and baptism | …, Födelse- och dopböcker [birth and baptism books] [vol], [years]']],
      page: [['B.2 §7', 'Birth and baptism | p. [P] (image [I]), no. [N], [Name] birth and baptism entry'], UNPAGINATED_PIN],
      author: [PARISH_AUTHOR_PIN],
      abbrev: [['B.2 §10', 'Födelse- och dopböcker | dopbok']],
      confidence: [['B.2 §8', "Birth and baptism | Very High (child's birth/baptism)"]],
    },
    examples: [],
  },
  {
    id: 'se-vigselbok', chapter: 'se', group: 'Parish records (kyrkoarkiv)', name: 'Lysnings- och vigselbok',
    hint: 'Banns and marriage book',
    source: PARISH_SOURCE, citation: PAGE_IMAGE_ENTRY, nouns: ['marriage entry'],
    defaults: VARMLAND_AD, confidence: 'High', doctype: 'vital record',
    title: 'Sweden, {lan}, {parish}, Lysnings- och Vigselbok [banns and marriage book] {vol}, {years}',
    abbrev: '{parish} vigselbok {vol} ({years})',
    author: '{parish} församling',
    page: '{pageLoc}, no. {entry}, {subject}',
    frn: `{parish} församling, Lysnings- och Vigselbok [banns and marriage book], vol. {vol} ({years}), {pageRef}, no. {entry}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{parish} vigselbok {vol} ({years}), {pageRef}, no. {entry}, {srnSubject}.',
    subjectLabel: 'Couple (Surname-Surname)',
    pins: {
      title: [['B.2 §4', 'Banns and marriage | …, Lysnings- och Vigselbok [banns and marriage book] [vol], [years]']],
      page: [['B.2 §7', 'Banns and marriage | p. [P] (image [I]), no. [N], [Surname]-[Surname] marriage entry'], UNPAGINATED_PIN],
      author: [PARISH_AUTHOR_PIN],
      abbrev: [['B.2 §10', 'Lysnings- och Vigselbok | vigselbok']],
      confidence: [['B.2 §8', 'Banns and marriage | High to Very High']],
    },
    examples: [],
  },
  {
    id: 'se-dodbok', chapter: 'se', group: 'Parish records (kyrkoarkiv)', name: 'Dödbok',
    hint: 'Death and burial book',
    source: PARISH_SOURCE, citation: PAGE_IMAGE_ENTRY, nouns: ['death entry', 'burial entry'],
    defaults: VARMLAND_AD, confidence: 'Very High', doctype: 'vital record',
    title: 'Sweden, {lan}, {parish}, Dödbok [death book] {vol}, {years}',
    abbrev: '{parish} dödbok {vol} ({years})',
    author: '{parish} församling',
    page: '{pageLoc}, no. {entry}, {subject}',
    frn: `{parish} församling, Dödbok [death book], vol. {vol} ({years}), {pageRef}, no. {entry}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{parish} dödbok {vol} ({years}), {pageRef}, no. {entry}, {srnSubject}.',
    pins: {
      title: [['B.2 §4', 'Death / burial | …, Dödbok [death book] [vol], [years]']],
      page: [['B.2 §7', 'Death / burial | p. [P] (image [I]), no. [N], [Name] death entry'], UNPAGINATED_PIN],
      author: [PARISH_AUTHOR_PIN],
      abbrev: [['B.2 §10', 'Dödbok | dödbok']],
      confidence: [['B.2 §8', 'Death/burial entry near the event | Very High']],
    },
    examples: [],
  },
  {
    id: 'se-confirmation', chapter: 'se', group: 'Parish records (kyrkoarkiv)', name: 'Confirmation or communion',
    hint: 'Recorded inside the husförhörslängd; cite it under that volume\'s Source.',
    source: PARISH_SOURCE, citation: PAGE_IMAGE, nouns: ['confirmation entry', 'communion entry'],
    defaults: VARMLAND_RA, confidence: 'High', doctype: 'religious',
    title: 'Sweden, {lan}, {parish}, Husförhörslängder [household examinations] {vol}, {years}',
    abbrev: '{parish} husförhörslängd {vol} ({years})',
    author: '{parish} församling',
    page: '{pageLoc}, {subject}',
    frn: `{parish} församling, Husförhörslängder [household examinations], vol. {vol} ({years}), {pageRef}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{parish} husförhörslängd {vol} ({years}), {pageRef}, {srnSubject}.',
    pins: {
      title: [['B.2 §4', "Confirmation and communion use the husförhörslängd's Title."]],
      page: [['B.2 §7', 'Confirmation / communion Pending review | p. [P] (image [I]), [Name] confirmation entry / communion entry'], UNPAGINATED_PIN],
      author: [PARISH_AUTHOR_PIN],
      confidence: [['B.2 §8', 'Confirmation Pending review | High']],
    },
    examples: [{
      guide: 'B.2 Example 4',
      inputs: {
        lan: 'Värmland', parish: 'Norra Ny', vol: 'AI:11', years: '1812–1820', call: 'SE/VA/13398/A I/11',
        page: '8', image: '19', name: 'Lars Persson', noun: 'confirmation entry',
        url: 'https://sok.riksarkivet.se/...', accessed: '20 April 2026',
      },
    }],
  },
  {
    id: 'se-sockenstamma', chapter: 'se', group: 'Parish records (kyrkoarkiv)', name: 'Sockenstämmoprotokoll',
    hint: 'Parish meeting minutes, a series of its own',
    source: PARISH_SOURCE,
    citation: [...PAGE_IMAGE, ['date', 'Meeting date or item no.', 'meeting of 3 May 1850']],
    nouns: ['parish meeting entry'],
    defaults: VARMLAND_AD, confidence: 'High', doctype: 'religious',
    title: 'Sweden, {lan}, {parish}, Sockenstämmoprotokoll [parish meeting minutes] {vol}, {years}',
    abbrev: '{parish} sockenstämmoprotokoll {vol} ({years})',
    author: '{parish} församling',
    page: '{pageLoc}, {date}, {subject}',
    frn: `{parish} församling, Sockenstämmoprotokoll [parish meeting minutes], vol. {vol} ({years}), {pageRef}, {date}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{parish} sockenstämmoprotokoll {vol} ({years}), {pageRef}, {srnSubject}.',
    pins: {
      title: [['B.2 §4', 'Meeting minutes Pending review | …, Sockenstämmoprotokoll [parish meeting minutes] [vol], [years]']],
      page: [['B.2 §7', 'Meeting minutes Pending review | p. [P] (image [I]), [date or item no.], [Name] parish meeting entry'], UNPAGINATED_PIN],
      author: [PARISH_AUTHOR_PIN],
      abbrev: [['B.2 §10', 'Sockenstämmoprotokoll Pending review | sockenstämmoprotokoll']],
      confidence: [['B.2 §8', "Meeting minutes Pending review | High for the meeting's business"]],
    },
    examples: [],
  },
  {
    id: 'se-bouppteckning', chapter: 'se', group: 'Court, census and land', name: 'Bouppteckning',
    hint: 'Estate inventory (häradsrätt); the locality is the härad, not the parish',
    source: [
      ['lan', 'Län', 'Värmland'], ['harad', 'Härad', 'Älvdals härad'], ['court', 'Court (creating body)', 'Älvdals häradsrätt'],
      ['cgloss', 'Court gloss', 'Älvdal district court'], ['vol', 'Volume', 'FII:26'], ['years', 'Years', '1832–1833'],
      ['call', 'Call number', 'SE/VA/11047/F II/26'],
    ],
    citation: [['pages', 'Pages', '203–205']],
    nouns: ['estate inventory'],
    defaults: VARMLAND_AD, confidence: 'High', doctype: 'legal',
    title: 'Sweden, {lan}, {harad}, Bouppteckningar [estate inventories] {vol}, {years}',
    abbrev: '{court} bouppteckning {vol} ({years})',
    author: '{court}',
    page: 'pp. {pages}, {subject}',
    frn: `{court} [{cgloss}], Bouppteckningar [estate inventories], vol. {vol} ({years}), pp. {pages}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}, {call}.`,
    srn: '{court} bouppteckning {vol} ({years}), pp. {pages}, {srnSubject}.',
    subjectLabel: 'Deceased',
    detailsLabel: 'Entry details (farm, parish, death)',
    pins: {
      title: [['B.2 §4', 'Estate inventory | Sweden, [län], [härad], Bouppteckningar [estate inventories] [vol], [years]']],
      page: [['B.2 §7', 'Estate inventory | pp. [P]–[P], [Deceased] estate inventory']],
      author: [['B.2 §2', 'Court and other state bodies | The creating body, e.g. Älvdals häradsrätt']],
      abbrev: [['B.2 §10', 'Bouppteckningar | bouppteckning | Älvdals häradsrätt bouppteckning FII:26 (1832–1833)']],
      confidence: [['B.2 §8', 'Bouppteckning | High']],
    },
    examples: [{
      guide: 'B.2 Example 2',
      inputs: {
        lan: 'Värmland', harad: 'Älvdals härad', court: 'Älvdals häradsrätt', cgloss: 'Älvdal district court',
        vol: 'FII:26', years: '1832–1833', call: 'SE/VA/11047/F II/26', pages: '203–205',
        name: 'Per Persson', noun: 'estate inventory',
        url: 'https://app.arkivdigital.se/volume/v48177?image=104', accessed: '20 April 2026', eventYear: '1832',
        details: 'Ambjörbymon, Norra Ny parish, died 5 May 1832',
      },
    }],
  },
  {
    id: 'se-folkrakning', chapter: 'se', group: 'Court, census and land', name: 'Folkräkning (SVAR)',
    hint: 'Census database; one Source per parish per count year',
    source: [['lan', 'Län', 'Värmland'], ['parish', 'Parish', 'Norra Ny'], ['year', 'Count year', '1880'], ['call', 'Call number', 'Folk_817085']],
    citation: [...PAGE_IMAGE, ['row', 'Row'], ['fam', 'Family no.']],
    nouns: ['household', 'census entry'],
    defaults: { platform: 'Riksarkivet', pubmedium: 'Database with images' },
    confidence: 'High', doctype: 'enumeration', eventDate: 'year',
    derive: v => ({ lanfull: lanFull(v.lan) }),
    title: 'Sweden, {lan}, {parish}, Folkräkning [census] {year}',
    abbrev: '{parish} folkräkning {year}',
    author: 'Riksarkivet',
    page: '{pageLoc}, row {row}, family no. {fam}, {subject}',
    frn: `Sveriges folkräkning {year} [Swedish census {year}], {parish} församling, {lanfull}, {pageRef}, row {row}, family no. {fam}, {entryof}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}.`,
    srn: '{parish} folkräkning {year}, {pageRef}, row {row}, {srnSubject}.',
    pins: {
      title: [['B.2 §4', 'SVAR census | Sweden, [län], [parish], Folkräkning [census] [year]']],
      page: [['B.2 §7', 'SVAR census | p. [P] (image [I]), row [R], family no. [F], [Head] household'], UNPAGINATED_PIN],
      author: [['B.2 §2', 'SVAR databases and other central records | Riksarkivet (covers SVAR)']],
      abbrev: [['B.2 §10', 'Folkräkning | folkräkning']],
      confidence: [['B.2 §8', 'SVAR with images | High residence; Normal ages']],
    },
    examples: [{
      guide: 'B.2 Example 3',
      inputs: {
        lan: 'Värmland', parish: 'Norra Ny', year: '1880', call: 'Folk_817085',
        page: '4', row: '33', fam: '1', name: 'Lars Persson Ambjörn', noun: 'household',
        url: 'https://sok.riksarkivet.se/bildvisning/Folk_817085-004', accessed: '21 April 2026',
        details: 'Ambjörby',
      },
    }],
  },
  {
    id: 'se-lantmateriet', chapter: 'se', group: 'Court, census and land', name: 'Lantmäteriet survey act',
    hint: 'Laga skifte, storskifte, ägodelning…; one numbered act = one Source',
    source: [
      ['lan', 'Län', 'Värmland'], ['parish', 'Parish', 'Norra Ny'], ['farm', 'Farm', 'Ambjörby'],
      ['stype', 'Survey type', 'laga skifte'], ['stgloss', 'Survey type gloss', 'statutory land enclosure'],
      ['act', 'Act number', '17-NON-148'], ['years', 'Years', '1856–1862'], ['call', 'Call number'],
    ],
    citation: [['protocol', 'Protocol locator', 'delningsbeskrivning p. 40']],
    note: [['survey', 'Survey details (FRN)', 'surveyed … by …, confirmed by … on …']],
    nouns: ['land allotment entry', 'signatory entry', 'croft transfer entry'],
    defaults: { platform: 'Lantmäteriet' },
    confidence: 'High', doctype: 'legal',
    derive: v => ({
      surveyAuthor: /^R/i.test(String(v.act || '').trim()) ? 'Lantmäteristyrelsen' : `Lantmäterimyndigheten i ${lanFull(v.lan) || gap('Län')}`,
    }),
    title: 'Sweden, {lan}, {parish}, {stype} [{stgloss}], act {act}, {years}',
    abbrev: '{parish} {stype} {act} ({years})',
    author: '{surveyAuthor}',
    page: '{protocol}, {subject}',
    frn: `{author}, {stype} [{stgloss}], {farm}, {parish} socken, act {act}«, {survey}»; {protocol}, {details}« (documenting {citedFor})»; ${DIGITAL_IMAGE}.`,
    srn: '{parish} {stype} {act} ({years}), {protocol}, {srnSubject}.',
    detailsLabel: 'Entry description (FRN)',
    paperlessTitle: '{farm} {stype} {eventYear}',
    pins: {
      title: [['B.2 §4', 'Land survey Pending review | Sweden, [län], [parish], [survey type] [English gloss], act [act-no], [years]']],
      page: [['B.2 §7', 'Land survey Pending review | [protocol locator], [name] [record-noun]']],
      author: [['B.2 §2', 'Land survey, NN-XXX-NNN county series (e.g. 17-NON-148) Pending review | Lantmäterimyndigheten i Värmlands län']],
      abbrev: [['B.2 §10', 'Land survey Pending review | ägodelning / storskifte / laga skifte / enskifte / gränsbestämning / avvittring']],
      confidence: [['B.2 §8', 'Land survey Pending review | High for what the surveyor recorded']],
      plTitle: [['C1', 'Land survey Pending review | Farm-led: [Farm] [survey type] [completion year]']],
    },
    examples: [{
      guide: 'B.2 Example 5',
      inputs: {
        lan: 'Värmland', parish: 'Norra Ny', farm: 'Ambjörby', stype: 'laga skifte', stgloss: 'statutory land enclosure',
        act: '17-NON-148', years: '1856–1862', protocol: 'delningsbeskrivning p. 40',
        name: 'Marit Andersdotter', noun: 'land allotment entry', says: 'Lott A, 64 öre 6 penningar', afterNoun: true,
        survey: 'surveyed 1856–1862 by O. Ignelius, confirmed by Älvdals övre tingslags egodelningsrätt 3 October 1863',
        details: 'land allotment (Lott A) of the minor Marit Andersdotter, 64 öre 6 penningar skatt',
        url: 'https://historiskakartor.lantmateriet.se', accessed: '16 June 2026', eventYear: '1862',
      },
    }],
  },
];
