// B.3 · US sources.
import { stateAbbrev } from '../tables.js';
import { gap } from '../template.js';

const DIGITAL_IMAGE = '{medium}, {platform} ({url} : accessed {accessed})';
const NARA_ANCESTRY = { platform: 'Ancestry', archive: 'National Archives' };
const NARA_FS = { platform: 'FamilySearch', archive: 'National Archives' };
const NARA_FOLD3 = { platform: 'Fold3', archive: 'National Archives' };
const MHS_ANCESTRY = { platform: 'Ancestry', archive: 'Minnesota Historical Society' };

export const US = [
  {
    id: 'us-federal-census', chapter: 'us', group: 'Census', name: 'Federal census',
    hint: 'One Source per county, state, and year; the roll goes in the page string',
    source: [['year', 'Census year', '1920'], ['county', 'County', 'St. Louis'], ['state', 'State', 'Minnesota'], ['call', 'NARA publication', 'T625']],
    citation: [['roll', 'Roll'], ['ed', 'ED'], ['sheet', 'Sheet', '8A'], ['dwelling', 'Dwelling'], ['family', 'Family']],
    note: [['locality', 'Locality (FRN)', 'Duluth']],
    nouns: ['household', 'census entry'],
    defaults: NARA_ANCESTRY, confidence: 'High', doctype: 'enumeration', eventDate: 'year',
    derive: v => ({ stab: stateAbbrev(v.state) }),
    title: '{year} U.S. Federal Census, {county} County, {state}',
    abbrev: '{county} Co., {stab}, {year} census',
    author: 'Bureau of the Census',
    page: 'roll {roll}, ED {ed}, sheet {sheet}, dwelling {dwelling}, family {family}, {subject}',
    frn: `{year} U.S. census, {county} County, {state}, population schedule, {locality}, enumeration district {ed}, sheet {sheet}, dwelling {dwelling}, family {family}, {subject}« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive} microfilm publication {call}, roll {roll}.`,
    frnMicrofilm: '{year} U.S. census, {county} County, {state}, population schedule, {locality}, enumeration district {ed}, sheet {sheet}, dwelling {dwelling}, family {family}, {subject}« (documenting {citedFor})»; {archive} microfilm publication {call}, roll {roll}.',
    srn: '{year} U.S. census, {county} Co., {stab}, pop. sched., {locality}, ED {ed}, sheet {sheet}, {subject}.',
    subjectLabel: 'Head (or person)',
    pins: {
      title: [['B.3 §4', 'Federal census | [year] U.S. Federal Census, [county] County, [state]']],
      page: [['B.3 §7', 'Federal census | roll [N], ED [N], sheet [N]A/B, dwelling [N], family [N], [Head] household']],
      author: [['B.3 §2', 'Federal census | Bureau of the Census']],
      confidence: [['B.3 §8', 'Federal census | High for residence and household; Normal for ages, birthplaces']],
    },
    examples: [{
      guide: 'B.3 Example 1',
      inputs: {
        year: '1920', county: 'St. Louis', state: 'Minnesota', call: 'T625',
        roll: '859', ed: '139', sheet: '8A', dwelling: '[N]', family: '[N]', name: 'Steve Maisuk', noun: 'household',
        locality: 'Duluth', url: 'https://www.ancestry.com/...', accessed: '6 May 2026',
      },
    }],
  },
  {
    id: 'us-state-census', chapter: 'us', group: 'Census', name: 'State census',
    hint: 'One Source per county, state, and year',
    source: [['year', 'Census year', '1905'], ['state', 'State', 'Minnesota'], ['county', 'County', 'St. Louis'], ['call', 'Call number']],
    citation: [['ward', 'Ward or township'], ['page', 'Page'], ['line', 'Line']],
    nouns: ['household', 'census entry'],
    defaults: MHS_ANCESTRY, confidence: 'High', doctype: 'enumeration', eventDate: 'year',
    derive: v => ({ stab: stateAbbrev(v.state) }),
    title: '{year} {state} State Census, {county} County',
    abbrev: '{county} Co., {stab}, {year} state census',
    author: '{state} Population Census Office',
    page: '{ward}, p. {page}, line {line}, {subject}',
    frn: `{year} {state} state census, {county} County, {ward}, p. {page}, line {line}, {subject}« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}.`,
    srn: '{year} {stab} state census, {county} Co., {ward}, p. {page}, {subject}.',
    subjectLabel: 'Head (or person)',
    pins: {
      title: [['B.3 §4', 'State census | [year] [state] State Census, [county] County']],
      page: [['B.3 §7', 'State census | [ward or township], p. [N], line [N], [Head] household']],
      author: [['B.3 §2', 'State census | [State] Population Census Office']],
    },
    examples: [],
  },
  {
    id: 'us-vital', chapter: 'us', group: 'Vital records', name: 'State vital record',
    hint: 'Death, birth, or marriage record; one Source per state collection',
    source: [['state', 'State', 'Minnesota'], ['series', 'Record series', 'death certificates'], ['years', 'Years', '1908–2002'], ['call', 'Call number (often blank)']],
    citation: [],
    pageVariants: [
      {
        key: 'certificate', label: 'Certificate',
        citation: [['cert', 'Certificate no.']],
        nouns: ['death certificate', 'birth certificate'],
        page: 'certificate no. {cert}, {subject}',
        frn: `{state}, {kind} no. {cert} ({eventYear}), {name}« (documenting {citedFor})»; {author}; ${DIGITAL_IMAGE}; citing {archive}.`,
        srn: '{stab} {kindShort} {cert} ({eventYear}), {name}.',
      },
      {
        key: 'license', label: 'Marriage license',
        citation: [['license', 'License no.']],
        nouns: ['marriage license'],
        page: 'license no. {license}, {subject}',
        frn: `{state}, marriage license no. {license} ({eventYear}), {name}« (documenting {citedFor})»; {author}; ${DIGITAL_IMAGE}; citing {archive}.`,
        srn: '{stab} marriage license {license} ({eventYear}), {name}.',
      },
    ],
    nouns: ['death certificate', 'birth certificate', 'marriage license'],
    defaults: { platform: 'FamilySearch', pubmedium: 'Database with images', archive: 'Minnesota Historical Society' },
    confidence: 'Very High', doctype: 'vital record',
    derive: v => {
      const series = String(v.series || '').toLowerCase();
      const kind = /birth/.test(series) ? 'birth certificate' : /marr/.test(series) ? 'marriage certificate' : 'death certificate';
      return {
        stab: stateAbbrev(v.state),
        kind,
        kindShort: { 'birth certificate': 'birth cert.', 'marriage certificate': 'marr. cert.', 'death certificate': 'death cert.' }[kind],
      };
    },
    title: '{state}, {series}, {years}',
    abbrev: '{stab} {series}, {years}',
    author: '{state} Department of Health, Vital Records',
    pins: {
      title: [['B.3 §4', 'State vital records | [State], [record series], [years]']],
      page: [
        ['B.3 §7', 'Death / birth certificate | certificate no. [N], [Name] death certificate / birth certificate'],
        ['B.3 §7', 'Marriage license | license no. [N], [Surname]-[Surname] marriage license'],
      ],
      author: [['B.3 §2', 'State vital records | [State] Department of Health, Vital Records']],
      confidence: [['B.3 §8', 'State death certificate (post-1900) | Very High for the death']],
    },
    examples: [{
      guide: 'B.3 Example 2',
      inputs: {
        state: 'Minnesota', series: 'death certificates', years: '1908–2002', variant: 'certificate',
        cert: '1929-MN-XXXXXX', name: 'Per Larsson Grund', noun: 'death certificate',
        url: 'https://www.familysearch.org/...', accessed: '6 May 2026', eventYear: '1929',
      },
    }],
  },
  {
    id: 'us-church', chapter: 'us', group: 'Vital records', name: 'Church record',
    hint: "Baptism, confirmation, marriage, burial; one Source per congregation's record set",
    source: [
      ['state', 'State', 'Minnesota'], ['county', 'County', 'Marshall'], ['town', 'Town', 'Warren'],
      ['church', 'Church', 'First Lutheran Church'], ['years', 'Years (Abbrev)', '1800–1952'], ['call', 'Archive reference'],
    ],
    citation: [['register', 'Register', 'death and burial register'], ['page', 'Page'], ['image', 'Image', 'if not the page']],
    note: [['collection', 'Digitized collection name'], ['citing', 'Citing, after the archive']],
    nouns: ['death and burial entry', 'baptism entry', 'confirmation entry', 'marriage entry', 'burial entry', 'membership entry'],
    defaults: { platform: 'Ancestry', archive: 'Swenson Swedish Immigration Research Center' },
    confidence: 'Very High', doctype: 'religious',
    derive: v => ({ stab: stateAbbrev(v.state) }),
    title: '{state}, {county} County, {town}, {church} records',
    abbrev: '{church}, {town}, {stab}, records«, {years}»',
    author: '{church}, {town}',
    page: '{register}, p. {page}« (image {image})», {subject}',
    frn: `{church} ({town}, {county} County, {state}), {register}, p. {page}« (image {image})», {details}« (documenting {citedFor})»; ${DIGITAL_IMAGE}«, "{collection}"»; citing {archive}«, {citing}».`,
    srn: '{church} ({town}, {stab}), {entryof}, p. {page}.',
    detailsLabel: 'Entry description (FRN)',
    pins: {
      title: [['B.3 §4', 'Church records Pending review | [State], [county], [town], [Church name] records']],
      page: [['B.3 §7', 'Church record Pending review | [register], p. [P] (image [I]), [Name] [record-noun]']],
      author: [['B.3 §2', 'Church records Pending review | [Church name], [town]']],
      confidence: [['B.3 §8', 'Church register Pending review | Very High for the recorded event']],
    },
    examples: [{
      guide: 'B.3 Example 11',
      inputs: {
        state: 'Minnesota', county: 'Marshall', town: 'Warren', church: 'First Lutheran Church', years: '1800–1952',
        register: 'death and burial register', page: '283', image: '496, right',
        name: 'Emma Söderström', noun: 'death and burial entry',
        details: 'death and burial of Emma Söderström, died 7 May 1914, buried 9 May 1914',
        url: 'https://www.ancestry.com/search/collections/61584/records/63230716', accessed: '16 June 2026', eventYear: '1914',
        collection: 'U.S., Evangelical Lutheran Church in America, Swedish American Church Records, 1800–1952',
        citing: 'Augustana College, Rock Island, Illinois',
      },
    }],
  },
  {
    id: 'us-naturalization', chapter: 'us', group: 'Immigration and military', name: 'Naturalization',
    hint: 'Petition or declaration of intention; one Source per court collection',
    source: [
      ['state', 'State', 'Minnesota'], ['county', 'County', 'St. Louis'], ['court', 'Court', 'St. Louis County District Court'],
      ['years', 'Years', '1888–1955'], ['call', 'Call number (microfilm)', 'SAM 227'],
    ],
    citation: [],
    note: [['courtplace', 'Court seat (FRN)', 'Duluth, Minnesota'], ['platformRef', 'Image group or collection ID (FRN)', 'Image Group Number 101714756, image 62']],
    pageVariants: [
      {
        key: 'petition', label: 'Petition',
        citation: [['pet', 'Petition no.']],
        nouns: ['naturalization petition'],
        page: 'petition no. {pet}, {subject}',
        frn: `{court} ({courtplace}), Naturalization Records, petition no. {pet} ({eventYear}), {name}« (documenting {citedFor})»; ${DIGITAL_IMAGE}«, {platformRef}»; citing {archive}« microfilm {call}».`,
        frnMicrofilm: '{court} ({courtplace}), Naturalization Records, petition no. {pet} ({eventYear}), {name}« (documenting {citedFor})»; {archive} microfilm {call}.',
        srn: '{county} Co. natz., pet. no. {pet} ({eventYear}), {name}.',
      },
      {
        key: 'declaration', label: 'Declaration of intention',
        citation: [['decl', 'Declaration no.']],
        nouns: ['declaration of intention'],
        page: 'declaration no. {decl}, {subject}',
        frn: `{court} ({courtplace}), Naturalization Records, declaration of intention no. {decl} ({eventYear}), {name}« (documenting {citedFor})»; ${DIGITAL_IMAGE}«, {platformRef}»; citing {archive}« microfilm {call}».`,
        frnMicrofilm: '{court} ({courtplace}), Naturalization Records, declaration of intention no. {decl} ({eventYear}), {name}« (documenting {citedFor})»; {archive} microfilm {call}.',
        srn: '{county} Co. natz., decl. no. {decl} ({eventYear}), {name}.',
      },
      {
        // Before 1906 a county court bound final papers in lettered volumes, usually without petition numbers.
        key: 'final', label: 'Final papers (before 1906)', eventDate: 'signed',
        citation: [
          ['reel', 'Microfilm reel', 'if known'], ['vol', 'Volume', 'C'], ['page', 'Page', 'blank if unnumbered'],
          ['image', 'Image', 'if not the page, or if unnumbered'], ['signed', 'Date signed', '12 March 1897'],
        ],
        nouns: ['naturalization petition'],
        page: '«reel {reel}, »final papers vol. {vol}, {pageLoc}, {subject}',
        frn: `{court} ({courtplace}), Naturalization Records, final papers vol. {vol}, {pageRef} ({signed}), {name}« (documenting {citedFor})»; ${DIGITAL_IMAGE}«, {platformRef}»; citing {archive}« microfilm {call}»«, reel {reel}».`,
        frnMicrofilm: '{court} ({courtplace}), Naturalization Records, final papers vol. {vol}, {pageRef} ({signed}), {name}« (documenting {citedFor})»; {archive} microfilm {call}«, reel {reel}».',
        srn: '{county} Co. natz., final papers vol. {vol}, {pageRef} ({eventYear}), {name}.',
      },
    ],
    nouns: ['naturalization petition', 'declaration of intention'],
    defaults: MHS_ANCESTRY, confidence: 'High', doctype: 'immigration',
    // The court takes the locality slot after its county: St. Louis County District Court → District Court.
    derive: v => {
      const court = String(v.court || '').trim(), county = `${String(v.county || '').trim()} County `;
      return { courtShort: !court ? gap('Court') : court.startsWith(county) ? court.slice(county.length) : court };
    },
    title: '{state}, {county} County, {courtShort}, Naturalization Records, {years}',
    abbrev: '{county} Co. naturalizations, {years}',
    author: '{court}',
    pins: {
      title: [['B.3 §4', 'Naturalization | [State], [county] County, [court], Naturalization Records, [years]']],
      page: [
        ['B.3 §7', 'Naturalization petition | petition no. [N], [Name] naturalization petition'],
        ['B.3 §7', 'Declaration of intention | declaration no. [N], [Name] declaration of intention'],
        ['B.3 §7', 'Final papers volume (before 1906) | reel [N], final papers vol. [V], p. [P] (image [I]), [Name] naturalization petition'],
        ['B.3 §7', 'With no page number, the image number takes the page\'s place: final papers vol. [V], image [I], [Name] naturalization petition'],
      ],
      author: [['B.3 §2', 'State/county court naturalization | [Court name]']],
      callNumber: [['B.3 §5', 'State archives microfilm (Minnesota Historical Society SAM 227) | Call number']],
      frnMicrofilm: [['B.3 §12', 'an FRN that ends with the film: …, Peter L. Grund; Minnesota Historical Society microfilm SAM 227, reel 4.'], ['A10', 'Film read in person has no URL or access date']],
      confidence: [['B.3 §8', 'Naturalization (declaration, petition, final papers) | High for the act recorded']],
    },
    examples: [{
      guide: 'B.3 Example 3',
      inputs: {
        state: 'Minnesota', court: 'St. Louis County District Court', county: 'St. Louis', years: '1888–1955', variant: 'petition',
        pet: '[N]', name: 'Per Larsson', noun: 'naturalization petition', courtplace: 'Duluth, Minnesota',
        url: 'https://www.ancestry.com/...', accessed: '6 May 2026', eventYear: '1894',
      },
    }, {
      guide: 'B.3 Example 12',
      inputs: {
        state: 'Minnesota', county: 'Marshall', court: 'Marshall County District Court', years: '1853–1967', call: 'SAM 227', variant: 'final',
        reel: '4', vol: 'C', page: '296', image: '[I]', signed: '12 March 1897', name: 'Peter L. Grund', noun: 'naturalization petition',
        courtplace: 'Warren, Minnesota', platform: 'FamilySearch', url: 'https://www.familysearch.org/ark:/61903/3:1:...', accessed: '[date]',
        platformRef: 'Image Group Number 101714756, image [I]',
      },
    }],
  },
  {
    id: 'us-draft-card', chapter: 'us', group: 'Immigration and military', name: 'WWII draft card',
    hint: 'Selective Service registration; one Source per state series',
    source: [['state', 'State', 'Minnesota'], ['call', 'Record group', 'RG 147']],
    citation: [['serial', 'Serial no.']],
    nouns: ['WWII draft card'],
    defaults: NARA_FS, confidence: 'High', doctype: 'military',
    derive: v => ({ stab: stateAbbrev(v.state), recordGroup: String(v.call || '').trim().replace(/^RG\s*/, 'Record Group ') }),
    title: 'World War II Draft Registration Cards, {state}',
    abbrev: 'WWII draft cards, {stab}',
    author: 'Selective Service System',
    page: 'serial no. {serial}, {subject}',
    frn: `{author}, World War II Draft Registration Cards, {state}, serial no. {serial}, {name} ({eventYear})« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {recordGroup}, {archive}.`,
    srn: 'WWII draft card, {stab}, {name}.',
    pins: {
      title: [['B.3 §4', 'WWII draft cards | World War II Draft Registration Cards, [state]']],
      page: [['B.3 §7', 'WWII draft card | serial no. [N], [Name] WWII draft card']],
      author: [['B.3 §2', 'WWII draft cards | Selective Service System']],
    },
    examples: [{
      guide: 'B.3 Example 5',
      inputs: {
        state: 'Minnesota', call: 'RG 147', serial: '[N]', name: 'Axel O. Grund', noun: 'WWII draft card',
        url: 'https://www.familysearch.org/...', accessed: '6 May 2026', eventYear: '1942',
      },
    }],
  },
  {
    id: 'us-headstone', chapter: 'us', group: 'Immigration and military', name: 'Headstone application',
    hint: 'Applications for Headstones series',
    source: [['years', 'Series years', '1925–1941'], ['call', 'Record group', 'RG 92']],
    citation: [['dyear', 'Death year']],
    note: [['citing', 'Citing clause', 'NAID …, Record Group 92, National Archives at …']],
    nouns: ['headstone application'],
    defaults: { platform: 'Ancestry' }, confidence: 'Normal', doctype: 'military', eventDate: 'dyear',
    title: 'Applications for Headstones for U.S. Military Veterans, {years}',
    abbrev: 'Headstone applications, {years}',
    author: 'Office of the Quartermaster General',
    page: '{name} (d. {dyear}) {noun}',
    frn: `{author}, "Applications for Headstones for U.S. Military Veterans, {years}," application for {name}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {citing}.`,
    srn: 'Headstone app., {name} (d. {dyear}).',
    detailsLabel: 'Application details (death date)',
    pins: {
      title: [['B.3 §4', 'Headstone applications | Applications for Headstones for U.S. Military Veterans, [years]']],
      page: [['B.3 §7', 'Headstone application | [Name] (d. [year]) headstone application']],
      author: [['B.3 §2', 'Headstone applications | Office of the Quartermaster General']],
      confidence: [['B.3 §8', 'Headstone application | Normal for death date; High for military service']],
    },
    examples: [{
      guide: 'B.3 Example 6',
      inputs: {
        years: '1925–1941', call: 'RG 92', dyear: '1948', name: 'Axel O. Grund', noun: 'headstone application',
        details: 'died 31 October 1948', url: 'https://www.ancestry.com/search/collections/2375/records/45037', accessed: '6 May 2026',
        citing: 'NAID 596118, Record Group 92, National Archives at Washington, DC',
      },
    }],
  },
  {
    id: 'us-civil-war-pension', chapter: 'us', group: 'Immigration and military', name: 'Civil War pension',
    hint: 'Civil War Pension Application Files (NARA RG 15)',
    source: [['call', 'Call number', 'RG 15']],
    citation: [['app', 'Application no.'], ['cert', 'Certificate no.']],
    nouns: ['pension file'],
    defaults: NARA_FOLD3, confidence: '', doctype: 'military',
    title: 'Civil War Pension Application Files',
    abbrev: 'Civil War pension files',
    author: 'Bureau of Pensions',
    page: 'application no. {app}, certificate no. {cert}, {subject}',
    frn: `{author}, Civil War Pension Application Files, application no. {app}, certificate no. {cert}, {name}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: 'Civil War pension, app. {app}, {name}.',
    pins: {
      title: [['B.3 §4', 'Civil War pensions | Civil War Pension Application Files']],
      page: [['B.3 §7', 'Civil War pension | application no. [N], certificate no. [N], [Name] pension file']],
      author: [['B.3 §2', 'Civil War pensions | Bureau of Pensions']],
    },
    examples: [],
  },
  {
    id: 'us-service-record', chapter: 'us', group: 'Immigration and military', name: 'Compiled service record',
    hint: 'Compiled military service records; one Source per series',
    source: [['series', 'Series title', 'Compiled Service Records of Volunteer Union Soldiers, Minnesota'], ['short', 'Short title (Abbrev)'], ['call', 'Call number']],
    citation: [['unit', 'Unit', 'Co. B, 1st Minnesota Infantry']],
    nouns: ['compiled service record'],
    defaults: NARA_FOLD3, confidence: '', doctype: 'military',
    title: '{series}',
    abbrev: '{short}',
    author: "War Department, Adjutant General's Office",
    page: '{unit}, {subject}',
    frn: `{author}, {series}, {unit}, {name}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, {call}».`,
    srn: '{short}, {unit}, {name}.',
    pins: {
      page: [['B.3 §7', 'Compiled service record | [Unit], [Name] compiled service record']],
      author: [['B.3 §2', "Compiled service records | War Department, Adjutant General's Office"]],
    },
    examples: [],
  },
  {
    id: 'us-passenger-manifest', chapter: 'us', group: 'Immigration and military', name: 'Passenger manifest',
    hint: 'One Source per arrival port and year-range series',
    source: [['port', 'Arrival port', 'New York'], ['years', 'Years', '1820–1957'], ['agency', 'Creating agency (Author)'], ['call', 'NARA publication']],
    citation: [['list', 'List'], ['line', 'Line']],
    nouns: [''],
    defaults: NARA_ANCESTRY, confidence: '', doctype: 'immigration',
    title: 'Passenger Lists of Vessels Arriving at {port}, {years}',
    abbrev: 'Passenger lists, {port}, {years}',
    author: '«{agency}»',
    page: 'list {list}, line {line}, {subject}',
    frn: `«{agency}, »"Passenger Lists of Vessels Arriving at {port}, {years}," list {list}, line {line}, {name}«, {details}»« (documenting {citedFor})»; ${DIGITAL_IMAGE}; citing {archive}«, microfilm publication {call}».`,
    srn: 'Passenger lists, {port}, list {list}, line {line}, {name}.',
    paperlessTitle: '{name} passenger manifest entry« {eventYear}»',
    pins: {
      title: [['B.3 §4', 'Passenger manifests | Passenger Lists of Vessels Arriving at [port], [years]']],
      page: [['B.3 §7', 'Passenger manifest | list [N], line [N], [Name]']],
      plTitle: [['C1', 'Passenger manifest | [Name] passenger manifest entry [year]']],
    },
    examples: [],
  },
  {
    id: 'us-find-a-grave', chapter: 'us', group: 'Cemeteries and publications', name: 'Find a Grave memorial',
    hint: 'One Source per cemetery; the memorial number goes in the page string',
    source: [['state', 'State', 'Minnesota'], ['county', 'County', 'St. Louis'], ['cemetery', 'Cemetery', 'Forest Hill Cemetery'], ['city', 'City', 'Duluth']],
    citation: [['memorial', 'Memorial no.']],
    note: [['life', 'Life dates (FRN)', '1848–1929'], ['photographer', 'Marker photo by, date (FRN)']],
    nouns: [''],
    defaults: { platform: 'Find a Grave', pubmedium: 'Database with images' },
    confidence: 'High', doctype: 'vital record',
    derive: v => ({ cemeteryShort: String(v.cemetery || '').replace(/\s+Cemetery$/i, '').trim() }),
    title: '{state}, {county} County, {cemetery}, Find a Grave Memorials',
    abbrev: '{cemeteryShort}, {city}, FAG',
    author: '',
    page: 'memorial no. {memorial}, {subject}',
    frn: 'Find a Grave, memorial no. {memorial}, {name}« ({life})», {cemetery}, {city}, {county} County, {state}« (documenting {citedFor})»; database with images, {platform} ({url} : accessed {accessed})«; marker photograph by {photographer}».',
    srn: 'FAG memorial {memorial}, {name}, {cemetery}.',
    paperlessTitle: '{name} Find a Grave memorial« {eventYear}»',
    pins: {
      title: [['B.3 §4', 'Find a Grave | [State], [county], [cemetery], Find a Grave Memorials']],
      page: [['B.3 §7', 'Find a Grave | memorial no. [N], [Name]']],
      author: [['B.3 §2', 'Newspapers, Find a Grave | Blank']],
      confidence: [['B.3 §8', 'Find a Grave with marker photo | High for burial and inscribed dates']],
      plTitle: [['C1', 'Find a Grave | [Name] Find a Grave memorial [year]']],
    },
    examples: [{
      guide: 'B.3 Example 4',
      inputs: {
        state: 'Minnesota', county: 'St. Louis', cemetery: 'Forest Hill Cemetery', city: 'Duluth',
        memorial: '[N]', name: 'Per Larsson Grund', noun: '', life: '1848–1929', photographer: '[contributor name], [date]',
        url: 'https://www.findagrave.com/memorial/[N]', accessed: '6 May 2026', eventYear: '1929',
      },
    }],
  },
  {
    id: 'us-newspaper', chapter: 'us', group: 'Cemeteries and publications', name: 'Newspaper item',
    hint: 'Obituary, funeral notice, announcement, or mention; one Source per newspaper title',
    source: [['paper', 'Newspaper', 'Warren Sheaf'], ['city', 'City', 'Warren'], ['state', 'State', 'Minnesota']],
    citation: [['date', 'Issue date', '3 December 1908'], ['page', 'Page'], ['col', 'Column no. (if given)'], ['column', 'Column name (a recurring column, not the headline)', 'Alma']],
    note: [['headline', 'Headline (FRN)', "The article's title, if it has one"]],
    nouns: ['obituary', 'funeral notice', 'marriage announcement', 'news mention'],
    defaults: { platform: 'Newspapers.com', archive: 'Minnesota Historical Society' },
    confidence: 'Normal', doctype: 'publication',
    title: '{paper}, {city}, {state}',
    abbrev: '{paper}',
    author: '',
    page: '{date}, p. {page}«, col. {col}»«, {column} column», {subject}',
    // An item can report many things, so the FRN names it by the page string's subject and says what it is
    // cited for, as the page string does (B.3 §7). The SRN is the paper and the page string.
    frn: `«"{headline}," »«"{column}" [column], »{paper} ({city}, {state}), {date}, p. {page}«, col. {col}», {subject}« (documenting {citedFor})»; ${DIGITAL_IMAGE}.`,
    // Read on a library's film, the issue date finds the reel, so the film is named without one.
    frnMicrofilm: '«"{headline}," »«"{column}" [column], »{paper} ({city}, {state}), {date}, p. {page}«, col. {col}», {subject}« (documenting {citedFor})»; {archive} microfilm.',
    srn: '{paper}, {date}, p. {page}«, col. {col}»«, {column} column», {subject}.',
    pins: {
      title: [['B.3 §4', 'Newspaper | [Title], [city, state]']],
      page: [
        ['B.3 §7', 'Newspaper wedding / funeral / obituary | [date], p. [N], col. [N], [Name] obituary (or marriage announcement, funeral notice)'],
        ['B.3 §7', 'Newspaper personals | [date], p. [N], col. [N], [Name] news mention'],
        ['B.3 §7', 'Mixed-subject column | [date], p. [N], col. [N], [Column name], [Name] news mention'],
      ],
      author: [['B.3 §2', 'Newspapers, Find a Grave | Blank']],
      pubinfo: [['B.3 §6', 'Newspapers read on a library\'s film use Microfilm, Minnesota Historical Society.']],
      citedFor: [['A7', 'A page string may end with what the citation is cited for, in parentheses after everything else'], ['A7', 'the FRN gives it as (documenting …) at the end of the item it describes, before the image, film, or holding clause'], ['A5', 'Citing in an FRN introduces only the source behind an image or film']],
      confidence: [['B.3 §8', 'Obituary | Normal at best']],
    },
    examples: [
      {
        guide: 'B.3 Example 8',
        inputs: {
          paper: 'Duluth Herald', city: 'Duluth', state: 'Minnesota', date: '14 July 1929', page: '7', col: '3',
          name: 'Per Larsson Grund', noun: 'obituary', headline: 'Per L. Grund, Duluth Pioneer, Dies at Williams Farm',
          url: 'https://www.newspapers.com/...', accessed: '6 May 2026', eventYear: '1929',
        },
      },
      {
        guide: 'B.3 Example 9',
        inputs: {
          paper: 'Warren Sheaf', city: 'Warren', state: 'Minnesota', date: '3 December 1908', page: '1',
          name: 'Grund-Hoiberg', noun: 'marriage announcement', headline: '[Headline if present]', confidence: 'High',
          url: 'https://www.newspapers.com/image/[N]', accessed: '6 May 2026', eventYear: '1908',
        },
      },
      {
        guide: 'B.3 Example 14',
        inputs: {
          paper: 'Warren Sheaf', city: 'Warren', state: 'Minnesota', date: '11 July 1917', page: '3', col: '1',
          name: 'Olaf Nygren household', noun: 'news mention', headline: 'This Honored Couple Celebrate Golden Wedding',
          citedFor: 'date and attendees', url: 'https://www.newspapers.com/article/warren-sheaf-mr-mrs-olaf-nygren-50th/12517574/',
          accessed: '4 October 2026', eventYear: '1917',
        },
      },
      {
        guide: 'B.3 Example 10', citation: 1,
        inputs: {
          paper: 'Warren Sheaf', city: 'Warren', state: 'Minnesota', date: '17 May 1916', page: '7', column: 'Alma',
          name: 'Peter Grund', noun: 'news mention',
          url: 'https://www.newspapers.com/image/64259642', accessed: '6 May 2026', eventYear: '1916',
        },
      },
      {
        guide: 'B.3 Example 10', citation: 2,
        inputs: {
          paper: 'Warren Sheaf', city: 'Warren', state: 'Minnesota', date: '17 May 1916', page: '7', column: 'Alma',
          name: 'John Olson', noun: 'news mention',
          url: 'https://www.newspapers.com/image/64259642', accessed: '6 May 2026', eventYear: '1916',
        },
      },
      {
        guide: 'B.3 Example 13', citation: 1,
        inputs: {
          paper: 'Warren Sheaf', city: 'Warren', state: 'Minnesota', date: '3 December 1908', page: '1',
          name: 'Grund-Hoiberg', noun: 'marriage announcement', headline: '[Headline if present]', confidence: 'High',
          url: 'https://www.newspapers.com/image/[N]', accessed: '6 May 2026', eventYear: '1908',
        },
      },
      {
        guide: 'B.3 Example 13', citation: 2,
        inputs: {
          paper: 'Warren Sheaf', city: 'Warren', state: 'Minnesota', date: '[date]', page: '[N]', col: '[N]',
          name: '[Name]', noun: 'obituary', headline: '[Headline]', pubmedium: 'Microfilm', archive: 'Minnesota Historical Society',
        },
      },
    ],
  },
  {
    id: 'us-city-directory', chapter: 'us', group: 'Cemeteries and publications', name: 'City directory',
    hint: 'One Source per annual directory; a publication, so Repository stays blank',
    source: [['dtitle', 'Directory title', "Polk's Duluth City Directory"], ['year', 'Year', '1900'], ['publisher', 'Publisher', 'R. L. Polk & Co.'], ['city', 'Place of publication', 'Duluth']],
    citation: [['page', 'Page']],
    nouns: ['directory entry'],
    defaults: { platform: 'Ancestry' },
    confidence: 'Normal', doctype: 'enumeration', eventDate: 'year',
    derive: v => {
      const title = String(v.dtitle || '').trim();
      return { dabbr: title.replace(/\s*City Directory$/i, ' directory'), dshort: title.replace(/\s*City Directory$/i, ' dir.') };
    },
    title: '{dtitle}, {year}',
    abbrev: '{dabbr}, {year}',
    author: '{publisher}',
    pubinfo: '{city}: {publisher}, {year}.« {pubmedium}, {platform} ({home}).»',
    page: 'p. {page}, {subject}',
    frn: '{publisher}, {dtitle}, {year} ({city}: {publisher}, {year}), p. {page}, {name}« (documenting {citedFor})»«; {medium}, {platform} ({url} : accessed {accessed})».',
    srn: '{dshort}, {year}, p. {page}, {name}.',
    pins: {
      title: [['B.3 §4', 'City directory | [Publisher] [city] City Directory, [year]']],
      page: [['B.3 §7', 'City directory | p. [N], [Name] directory entry']],
      author: [['B.3 §2', 'City directories | [Publisher]']],
      pubinfo: [['B.3 §6', 'Published directories use the imprint variant (Example 7).']],
      confidence: [['B.3 §8', 'City directory | Normal for residence']],
    },
    examples: [{
      guide: 'B.3 Example 7',
      inputs: {
        dtitle: "Polk's Duluth City Directory", year: '1900', publisher: 'R. L. Polk & Co.', city: 'Duluth',
        page: '412', name: 'Per Larsson Grund', noun: 'directory entry',
        url: 'https://www.ancestry.com/...', accessed: '6 May 2026',
      },
    }],
  },
];
