"""Faces module — person links and face-rectangle MediaRefs.

One mental model: the Gramps rect for a (person, photo) face is always the
materialization of Immich's detected box + a per-face padding value. Editing
the pad recomputes the rect; a face whose rect is missing or stale is
"pending"; the Sync/ManualFaces tag is an informational alert (its only
behavioral effect is a 0% *default* pad), not a lock.

SQLite is the source of truth for links and pads, with a write-through
person_map.yaml export for the legacy pipeline (removed in Phase 2).
"""

from __future__ import annotations

import asyncio
import logging
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import AsyncIterator

import yaml

from ..core.clients import GrampsClient, ImmichClient
from ..core.clients.gramps import person_display_name
from ..core.events import SyncEvent

log = logging.getLogger("bifrost.faces")

DEFAULT_PAD = 0.15
MANUAL_FACES_TAG = "Sync/ManualFaces"
# Phase 2 moves this into config with the sync module; faces only needs it to
# show "tagged but not yet synced" photos in the grid.
SYNC_TAG = "Sync/Gramps"
IMMICH_ID_ATTR = "Immich ID"
CONCURRENCY = 8

PERSON_MAP_HEADER = """# Person mapping between Gramps and Immich
#
# GENERATED BY BIFROST — do not hand-edit; edit links in the Bifrost faces
# page instead. This export exists so the legacy immich_to_gramps.py
# --link-faces keeps working until bifrost's sync module replaces it.

"""


# ---------------------------------------------------------------------------
# Pure functions
# ---------------------------------------------------------------------------

def immich_face_to_gramps_rect(face: dict, pad_factor: float = 0.0) -> list[int] | None:
    """Convert an Immich face bounding box to Gramps rect percentages.

    Immich provides boundingBoxX1/Y1/X2/Y2 in pixels plus imageWidth/Height.
    Gramps expects [left, top, right, bottom] as integer percentages (0-100).
    pad_factor expands the box outward by that fraction of its width/height on
    each side before converting; the result clamps to [0, 100].
    """
    iw = face.get("imageWidth")
    ih = face.get("imageHeight")
    if not iw or not ih:
        return None

    x1 = face.get("boundingBoxX1", 0)
    y1 = face.get("boundingBoxY1", 0)
    x2 = face.get("boundingBoxX2", 0)
    y2 = face.get("boundingBoxY2", 0)

    if pad_factor > 0:
        bw = x2 - x1
        bh = y2 - y1
        x1 -= bw * pad_factor
        x2 += bw * pad_factor
        y1 -= bh * pad_factor
        y2 += bh * pad_factor

    return [
        max(0, min(100, round(x1 * 100 / iw))),
        max(0, min(100, round(y1 * 100 / ih))),
        max(0, min(100, round(x2 * 100 / iw))),
        max(0, min(100, round(y2 * 100 / ih))),
    ]


def face_status(current_rect: list | None, expected_rect: list | None) -> str:
    if current_rect is None:
        return "pending"
    if expected_rect is not None and list(current_rect) != list(expected_rect):
        return "outdated"
    return "applied"


# Pads worth recognizing when adopting pre-bifrost rects as intent (tight and
# the legacy default; finer values were never produced by the old pipeline).
ADOPTABLE_PADS = (0.0, DEFAULT_PAD)


# ---------------------------------------------------------------------------
# Person links (SQLite is the source of truth; YAML export is a compat shim)
# ---------------------------------------------------------------------------

def list_links(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute(
        "SELECT gramps_handle, immich_person_id, label FROM person_links ORDER BY rowid"
    ).fetchall()
    out = []
    for r in rows:
        entry = {"gramps_handle": r["gramps_handle"], "immich_person_id": r["immich_person_id"]}
        if r["label"]:
            entry["label"] = r["label"]
        out.append(entry)
    return out


def person_map_dict(conn: sqlite3.Connection) -> dict[str, str]:
    """{immich_person_id: gramps_handle} — the shape the apply logic wants."""
    return {e["immich_person_id"]: e["gramps_handle"] for e in list_links(conn)}


def set_link(
    conn: sqlite3.Connection,
    gramps_handle: str,
    immich_person_id: str,
    label: str | None,
    export_path: Path | None,
) -> list[dict]:
    """Create or replace the link for a Gramps person (legacy semantics:
    one Immich person per Gramps handle)."""
    now = datetime.now().isoformat(timespec="seconds")
    with conn:
        conn.execute("DELETE FROM person_links WHERE gramps_handle = ?", (gramps_handle,))
        conn.execute(
            "INSERT INTO person_links (gramps_handle, immich_person_id, label, created_at)"
            " VALUES (?, ?, ?, ?)",
            (gramps_handle, immich_person_id, (label or "").strip() or None, now),
        )
    export_person_map(conn, export_path)
    return list_links(conn)


def delete_link(
    conn: sqlite3.Connection, gramps_handle: str, export_path: Path | None
) -> bool:
    with conn:
        cur = conn.execute(
            "DELETE FROM person_links WHERE gramps_handle = ?", (gramps_handle,)
        )
    if cur.rowcount == 0:
        return False
    export_person_map(conn, export_path)
    return True


def export_person_map(conn: sqlite3.Connection, path: Path | None) -> None:
    """Write-through shim: regenerate the legacy person_map.yaml."""
    if path is None:
        return
    if not path.parent.is_dir():
        log.warning("person_map export dir missing (%s) — skipping export", path.parent)
        return
    with open(path, "w") as fh:
        fh.write(PERSON_MAP_HEADER)
        yaml.dump(
            {"people": list_links(conn)},
            fh, sort_keys=False, default_flow_style=False, allow_unicode=True,
        )
    log.info("Exported person map to %s", path)


# ---------------------------------------------------------------------------
# Per-face padding
# ---------------------------------------------------------------------------

def get_stored_pad(conn: sqlite3.Connection, handle: str, asset_id: str) -> float | None:
    row = conn.execute(
        "SELECT pad FROM face_pads WHERE gramps_handle=? AND asset_id=?",
        (handle, asset_id),
    ).fetchone()
    return row["pad"] if row else None


def set_stored_pad(conn: sqlite3.Connection, handle: str, asset_id: str, pad: float) -> None:
    with conn:
        conn.execute(
            "INSERT OR REPLACE INTO face_pads (gramps_handle, asset_id, pad, updated_at)"
            " VALUES (?, ?, ?, ?)",
            (handle, asset_id, pad, datetime.now().isoformat(timespec="seconds")),
        )


def effective_pad(
    conn: sqlite3.Connection, handle: str, asset_id: str, is_manual: bool
) -> float:
    stored = get_stored_pad(conn, handle, asset_id)
    if stored is not None:
        return stored
    return 0.0 if is_manual else DEFAULT_PAD


# ---------------------------------------------------------------------------
# Shared lookups
# ---------------------------------------------------------------------------

async def synced_immich_media(gramps: GrampsClient) -> dict[str, dict]:
    """{immich_asset_id: gramps_media_obj} for media with an Immich ID attribute."""
    synced: dict[str, dict] = {}
    for m in await gramps.list_media():
        for attr in m.get("attribute_list", []):
            if attr.get("type") == IMMICH_ID_ATTR:
                synced[attr["value"]] = m
                break
    return synced


async def manual_face_asset_ids(immich: ImmichClient) -> set[str]:
    try:
        tag_id = await immich.resolve_tag_id(MANUAL_FACES_TAG)
        if not tag_id:
            return set()
        return await immich.search_asset_ids_by_tag(tag_id)
    except Exception as exc:  # noqa: BLE001 — tag lookup is best-effort
        log.warning("Could not look up %s tag: %s", MANUAL_FACES_TAG, exc)
        return set()


async def _gather_limited(coros: list) -> list:
    sem = asyncio.Semaphore(CONCURRENCY)

    async def run(c):
        async with sem:
            return await c

    return await asyncio.gather(*(run(c) for c in coros))


# ---------------------------------------------------------------------------
# Photo listing — the workhorse behind the Photos view
# ---------------------------------------------------------------------------

async def photo_listing(
    gramps: GrampsClient, immich: ImmichClient, conn: sqlite3.Connection
) -> dict:
    """Everything the Photos view needs, in one structure:

    photos: [{asset_id, title, gramps_id, media_handle, synced, is_manual,
              pending_count, faces: [{immich_person_id, immich_name,
              gramps_handle, label, pad, current_rect, expected_rect,
              status: applied|outdated|pending|unlinked}]}]
    """
    links = list_links(conn)
    by_immich = {e["immich_person_id"]: e for e in links}
    manual = await manual_face_asset_ids(immich)
    synced = await synced_immich_media(gramps)

    # Linked Gramps people, fetched once each (media_list carries the rects)
    handles = sorted({e["gramps_handle"] for e in links})
    fetched = await _gather_limited([gramps.get_person(h) for h in handles])
    persons: dict[str, dict] = {}
    for h, p in zip(handles, fetched):
        persons[h] = p

    # Faces per synced asset
    asset_ids = list(synced.keys())
    faces_lists = await _gather_limited([immich.get_faces(a) for a in asset_ids])
    faces_by_asset = dict(zip(asset_ids, faces_lists))

    photos = []
    for asset_id, media_obj in synced.items():
        media_handle = media_obj["handle"]
        is_manual = asset_id in manual
        face_rows = []
        for face in faces_by_asset.get(asset_id, []):
            ip = face.get("person") or {}
            ipid = ip.get("id")
            if not ipid:
                continue  # unassigned ML detection — nothing to act on yet
            link = by_immich.get(ipid)
            if not link:
                face_rows.append({
                    "immich_person_id": ipid,
                    "immich_name": ip.get("name") or "(unnamed)",
                    "status": "unlinked",
                })
                continue
            handle = link["gramps_handle"]
            person = persons.get(handle) or {}
            pad = effective_pad(conn, handle, asset_id, is_manual)
            expected = immich_face_to_gramps_rect(face, pad_factor=pad)
            current = next(
                (mr.get("rect") for mr in person.get("media_list", [])
                 if mr.get("ref") == media_handle and mr.get("rect")),
                None,
            )
            status = face_status(current, expected)

            # Adopt pre-bifrost intent: a rect that matches a recognizable pad
            # isn't drift — record that pad instead of flagging it.
            if (
                status == "outdated"
                and get_stored_pad(conn, handle, asset_id) is None
            ):
                for candidate in ADOPTABLE_PADS:
                    adopted = immich_face_to_gramps_rect(face, pad_factor=candidate)
                    if adopted is not None and list(current) == adopted:
                        set_stored_pad(conn, handle, asset_id, candidate)
                        pad, expected, status = candidate, adopted, "applied"
                        break

            # On manual-faces photos a mismatch is protected, not pending:
            # the rect may be a deliberate human choice. Individual apply
            # (with the warning banner in view) is the only way to touch it.
            if status == "outdated" and is_manual:
                status = "differs"

            face_rows.append({
                "immich_person_id": ipid,
                "immich_name": ip.get("name") or "(unnamed)",
                "gramps_handle": handle,
                "gramps_id": person.get("gramps_id"),
                "label": link.get("label") or (person_display_name(person) if person else None),
                "pad": pad,
                "current_rect": current,
                "expected_rect": expected,
                "status": status,
            })
        photos.append({
            "asset_id": asset_id,
            "title": media_obj.get("desc") or asset_id[:8],
            "gramps_id": media_obj.get("gramps_id", ""),
            "media_handle": media_handle,
            "synced": True,
            "is_manual": is_manual,
            "pending_count": sum(1 for f in face_rows if f["status"] in ("pending", "outdated")),
            "faces": face_rows,
        })

    # Tagged-but-unsynced assets: visible (greyed) so media creation has an
    # honest home here when the sync module lands in Phase 2.
    try:
        sync_tag = await immich.resolve_tag_id(SYNC_TAG)
        if sync_tag:
            for item in await immich.search_assets_by_tag(sync_tag):
                if item["id"] in synced:
                    continue
                photos.append({
                    "asset_id": item["id"],
                    "title": item.get("originalFileName") or item["id"][:8],
                    "gramps_id": None,
                    "media_handle": None,
                    "synced": False,
                    "is_manual": item["id"] in manual,
                    "pending_count": 0,
                    "faces": [],
                })
    except Exception as exc:  # noqa: BLE001 — grid still useful without these
        log.warning("Could not list unsynced tagged assets: %s", exc)

    photos.sort(key=lambda p: ((not p["synced"]), p["title"].lower()))
    return {
        "photos": photos,
        "pending_total": sum(p["pending_count"] for p in photos),
    }


# ---------------------------------------------------------------------------
# Apply — the single-face atom and the one bulk action
# ---------------------------------------------------------------------------

async def apply_face(
    gramps: GrampsClient,
    immich: ImmichClient,
    conn: sqlite3.Connection,
    gramps_handle: str,
    asset_id: str,
    pad: float,
    media_handle: str | None = None,
) -> dict:
    """Set this face's pad and materialize its rect in Gramps (create the
    MediaRef if missing, update its rect otherwise). Returns the new state.

    Pass media_handle when the caller already knows it (e.g. the sync module
    right after creating the media) to skip the synced-media lookup."""
    pad = max(0.0, min(0.5, pad))
    link = next(
        (e for e in list_links(conn) if e["gramps_handle"] == gramps_handle), None
    )
    if link is None:
        raise ValueError("no link for this Gramps person")

    if media_handle is None:
        synced = await synced_immich_media(gramps)
        media_obj = synced.get(asset_id)
        if media_obj is None:
            raise ValueError("asset is not synced to Gramps")
        media_handle = media_obj["handle"]

    face = next(
        (f for f in await immich.get_faces(asset_id)
         if (f.get("person") or {}).get("id") == link["immich_person_id"]),
        None,
    )
    if face is None:
        raise ValueError("Immich no longer detects this person's face on this asset")

    rect = immich_face_to_gramps_rect(face, pad_factor=pad)
    if rect is None:
        raise ValueError("face has no usable bounding box")

    person = await gramps.get_person(gramps_handle)
    refs = person.setdefault("media_list", [])
    existing = next((mr for mr in refs if mr.get("ref") == media_handle), None)
    if existing is not None:
        existing["rect"] = rect
    else:
        refs.append({
            "_class": "MediaRef",
            "ref": media_handle,
            "rect": rect,
            "attribute_list": [],
            "citation_list": [],
            "note_list": [],
            "private": False,
        })
    await gramps.update_person(gramps_handle, person)
    set_stored_pad(conn, gramps_handle, asset_id, pad)

    return {
        "gramps_handle": gramps_handle,
        "asset_id": asset_id,
        "pad": pad,
        "current_rect": rect,
        "expected_rect": rect,
        "status": "applied",
    }


async def apply_pending(
    gramps: GrampsClient,
    immich: ImmichClient,
    conn: sqlite3.Connection,
) -> AsyncIterator[SyncEvent]:
    """Materialize every pending/outdated face using its effective pad."""
    listing = await photo_listing(gramps, immich, conn)
    todo = [
        (p, f)
        for p in listing["photos"]
        for f in p["faces"]
        if f["status"] in ("pending", "outdated")
    ]
    yield SyncEvent(kind="started", detail=f"{len(todo)} pending face(s)")

    counts = {"created": 0, "updated": 0, "failed": 0}
    for photo, face in todo:
        action = "created" if face["status"] == "pending" else "updated"
        try:
            await apply_face(
                gramps, immich, conn,
                face["gramps_handle"], photo["asset_id"], face["pad"],
            )
        except Exception as exc:  # noqa: BLE001
            counts["failed"] += 1
            yield SyncEvent(
                kind="item", entity="face", action="failed",
                source_id=photo["asset_id"],
                title=f"{face.get('label') or face['immich_name']} on '{photo['title']}'",
                detail=str(exc),
            )
            continue
        counts[action] += 1
        yield SyncEvent(
            kind="item", entity="face", action=action,
            source_id=photo["asset_id"],
            gramps_id=face.get("gramps_id"),
            title=f"{face.get('label') or face['immich_name']} on '{photo['title']}'",
            data={"rect": face["expected_rect"], "pad": face["pad"]},
        )

    yield SyncEvent(kind="summary", data=counts)
