"""Faces module — person links and face-rectangle MediaRefs.

Ported from immich-to-gramps (person_linker_gui.py + run_link_faces /
run_repad_faces in immich_to_gramps.py), with bifrost's SQLite as the source
of truth for links and a write-through person_map.yaml export for the legacy
pipeline (removed in Phase 2).

Long operations (link_faces, repad_faces) are async generators yielding
SyncEvents; preview is the same generator with apply=False.
"""

from __future__ import annotations

import logging
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import AsyncIterator

import yaml

from ..core.clients import GrampsClient, ImmichClient
from ..core.clients.gramps import person_display_name
from ..core.events import SyncEvent

log = logging.getLogger("bifrost.faces")

# Default expansion applied to Immich face boxes when writing them to Gramps.
# 0.15 grows each side by 15% of the box dimension. Assets tagged
# Sync/ManualFaces opt out (tight crop, and re-pad leaves them alone).
FACE_PAD_FACTOR = 0.15
MANUAL_FACES_TAG = "Sync/ManualFaces"
IMMICH_ID_ATTR = "Immich ID"

PERSON_MAP_HEADER = """# Person mapping between Gramps and Immich
#
# GENERATED BY BIFROST — do not hand-edit; edit links in the Bifrost faces
# page instead. This export exists so the legacy immich_to_gramps.py
# --link-faces keeps working until bifrost's sync module replaces it.

"""


# ---------------------------------------------------------------------------
# Pure functions
# ---------------------------------------------------------------------------

def immich_face_to_gramps_rect(face: dict, pad_factor: float = 0.0) -> list[int] | None:
    """Convert an Immich face bounding box to Gramps rect percentages.

    Immich provides boundingBoxX1/Y1/X2/Y2 in pixels plus imageWidth/Height.
    Gramps expects [left, top, right, bottom] as integer percentages (0-100).
    pad_factor expands the box outward by that fraction of its width/height on
    each side before converting; the result clamps to [0, 100].
    """
    iw = face.get("imageWidth")
    ih = face.get("imageHeight")
    if not iw or not ih:
        return None

    x1 = face.get("boundingBoxX1", 0)
    y1 = face.get("boundingBoxY1", 0)
    x2 = face.get("boundingBoxX2", 0)
    y2 = face.get("boundingBoxY2", 0)

    if pad_factor > 0:
        bw = x2 - x1
        bh = y2 - y1
        x1 -= bw * pad_factor
        x2 += bw * pad_factor
        y1 -= bh * pad_factor
        y2 += bh * pad_factor

    return [
        max(0, min(100, round(x1 * 100 / iw))),
        max(0, min(100, round(y1 * 100 / ih))),
        max(0, min(100, round(x2 * 100 / iw))),
        max(0, min(100, round(y2 * 100 / ih))),
    ]


# ---------------------------------------------------------------------------
# Person links (SQLite is the source of truth; YAML export is a compat shim)
# ---------------------------------------------------------------------------

def list_links(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute(
        "SELECT gramps_handle, immich_person_id, label FROM person_links ORDER BY rowid"
    ).fetchall()
    out = []
    for r in rows:
        entry = {"gramps_handle": r["gramps_handle"], "immich_person_id": r["immich_person_id"]}
        if r["label"]:
            entry["label"] = r["label"]
        out.append(entry)
    return out


def person_map_dict(conn: sqlite3.Connection) -> dict[str, str]:
    """{immich_person_id: gramps_handle} — the shape the apply logic wants."""
    return {
        e["immich_person_id"]: e["gramps_handle"] for e in list_links(conn)
    }


def set_link(
    conn: sqlite3.Connection,
    gramps_handle: str,
    immich_person_id: str,
    label: str | None,
    export_path: Path | None,
) -> list[dict]:
    """Create or replace the link for a Gramps person (legacy semantics:
    one Immich person per Gramps handle)."""
    now = datetime.now().isoformat(timespec="seconds")
    with conn:
        conn.execute("DELETE FROM person_links WHERE gramps_handle = ?", (gramps_handle,))
        conn.execute(
            "INSERT INTO person_links (gramps_handle, immich_person_id, label, created_at)"
            " VALUES (?, ?, ?, ?)",
            (gramps_handle, immich_person_id, (label or "").strip() or None, now),
        )
    export_person_map(conn, export_path)
    return list_links(conn)


def delete_link(
    conn: sqlite3.Connection, gramps_handle: str, export_path: Path | None
) -> bool:
    with conn:
        cur = conn.execute(
            "DELETE FROM person_links WHERE gramps_handle = ?", (gramps_handle,)
        )
    if cur.rowcount == 0:
        return False
    export_person_map(conn, export_path)
    return True


def export_person_map(conn: sqlite3.Connection, path: Path | None) -> None:
    """Write-through shim: regenerate the legacy person_map.yaml."""
    if path is None:
        return
    if not path.parent.is_dir():
        log.warning("person_map export dir missing (%s) — skipping export", path.parent)
        return
    with open(path, "w") as fh:
        fh.write(PERSON_MAP_HEADER)
        yaml.dump(
            {"people": list_links(conn)},
            fh, sort_keys=False, default_flow_style=False, allow_unicode=True,
        )
    log.info("Exported person map to %s", path)


# ---------------------------------------------------------------------------
# Shared lookups
# ---------------------------------------------------------------------------

async def synced_immich_media(gramps: GrampsClient) -> dict[str, dict]:
    """{immich_asset_id: gramps_media_obj} for media with an Immich ID attribute."""
    synced: dict[str, dict] = {}
    for m in await gramps.list_media():
        for attr in m.get("attribute_list", []):
            if attr.get("type") == IMMICH_ID_ATTR:
                synced[attr["value"]] = m
                break
    return synced


async def manual_face_asset_ids(immich: ImmichClient) -> set[str]:
    try:
        tag_id = await immich.resolve_tag_id(MANUAL_FACES_TAG)
        if not tag_id:
            return set()
        return await immich.search_asset_ids_by_tag(tag_id)
    except Exception as exc:  # noqa: BLE001 — tag lookup is best-effort
        log.warning("Could not look up %s tag: %s", MANUAL_FACES_TAG, exc)
        return set()


# ---------------------------------------------------------------------------
# Apply operations (async generators of SyncEvents)
# ---------------------------------------------------------------------------

async def link_faces(
    gramps: GrampsClient,
    immich: ImmichClient,
    conn: sqlite3.Connection,
    apply: bool,
) -> AsyncIterator[SyncEvent]:
    """Scan synced media for Immich faces of linked people; add face-rectangle
    MediaRefs to the matching Gramps people (port of run_link_faces)."""
    person_map = person_map_dict(conn)
    yield SyncEvent(kind="started", detail=f"{len(person_map)} person links loaded")
    if not person_map:
        yield SyncEvent(kind="summary", data={"linked": 0})
        return

    manual = await manual_face_asset_ids(immich)
    synced = await synced_immich_media(gramps)
    yield SyncEvent(kind="started", detail=f"{len(synced)} synced media to scan")

    counts = {"created": 0, "skipped": 0, "failed": 0}
    person_cache: dict[str, dict] = {}

    for asset_id, media_obj in synced.items():
        media_handle = media_obj["handle"]
        media_title = media_obj.get("desc") or asset_id[:8]
        media_gid = media_obj.get("gramps_id", "?")
        pad = 0.0 if asset_id in manual else FACE_PAD_FACTOR

        try:
            faces = await immich.get_faces(asset_id)
        except Exception as exc:  # noqa: BLE001
            yield SyncEvent(
                kind="error", entity="face", source_id=asset_id,
                detail=f"could not fetch faces: {exc}",
            )
            counts["failed"] += 1
            continue

        for face in faces:
            person = face.get("person") or {}
            immich_pid = person.get("id")
            handle = person_map.get(immich_pid) if immich_pid else None
            if not handle:
                continue
            immich_name = person.get("name") or immich_pid[:8]

            if handle not in person_cache:
                try:
                    person_cache[handle] = await gramps.get_person(handle)
                except Exception as exc:  # noqa: BLE001
                    yield SyncEvent(
                        kind="error", entity="face", source_id=asset_id,
                        detail=f"could not fetch Gramps person {handle[:12]}: {exc}",
                    )
                    counts["failed"] += 1
                    person_cache[handle] = {}
                    continue
            gramps_person = person_cache[handle]
            if not gramps_person:
                continue

            refs = gramps_person.setdefault("media_list", [])
            if any(mr.get("ref") == media_handle for mr in refs):
                counts["skipped"] += 1
                continue

            rect = immich_face_to_gramps_rect(face, pad_factor=pad)
            gramps_name = person_display_name(gramps_person)
            event = SyncEvent(
                kind="item", entity="face",
                action="created" if apply else "would_create",
                source_id=asset_id,
                gramps_id=gramps_person.get("gramps_id"),
                title=f"{immich_name} → {gramps_name} on '{media_title}'",
                data={"rect": rect, "media_gramps_id": media_gid,
                      "media_handle": media_handle, "pad": pad},
            )

            if apply:
                refs.append({
                    "_class": "MediaRef",
                    "ref": media_handle,
                    "rect": rect,
                    "attribute_list": [],
                    "citation_list": [],
                    "note_list": [],
                    "private": False,
                })
                try:
                    await gramps.update_person(handle, gramps_person)
                except Exception as exc:  # noqa: BLE001
                    refs.pop()
                    event = SyncEvent(
                        kind="item", entity="face", action="failed",
                        source_id=asset_id, title=event.title,
                        detail=str(exc),
                    )
                    counts["failed"] += 1
                    yield event
                    continue
            counts["created"] += 1
            yield event

    yield SyncEvent(kind="summary", data=counts)


async def repad_faces(
    gramps: GrampsClient,
    immich: ImmichClient,
    conn: sqlite3.Connection,
    apply: bool,
) -> AsyncIterator[SyncEvent]:
    """Recompute rects on existing Immich-sourced face MediaRefs to apply the
    current padding (port of run_repad_faces). Sync/ManualFaces assets are
    skipped entirely."""
    person_map = person_map_dict(conn)
    yield SyncEvent(kind="started", detail=f"{len(person_map)} person links loaded")
    if not person_map:
        yield SyncEvent(kind="summary", data={"updated": 0})
        return

    manual = await manual_face_asset_ids(immich)
    synced = await synced_immich_media(gramps)
    by_handle = {m["handle"]: (aid, m) for aid, m in synced.items()}
    yield SyncEvent(kind="started", detail=f"{len(by_handle)} Immich-sourced media in Gramps")

    counts = {"updated": 0, "unchanged": 0, "skipped": 0, "failed": 0}
    faces_cache: dict[str, list[dict]] = {}

    async def faces_for(asset_id: str) -> list[dict]:
        if asset_id not in faces_cache:
            try:
                faces_cache[asset_id] = await immich.get_faces(asset_id)
            except Exception as exc:  # noqa: BLE001
                log.warning("Could not fetch faces for %s: %s", asset_id[:8], exc)
                faces_cache[asset_id] = []
        return faces_cache[asset_id]

    for immich_pid, handle in person_map.items():
        try:
            person = await gramps.get_person(handle)
        except Exception as exc:  # noqa: BLE001
            yield SyncEvent(kind="error", entity="face",
                            detail=f"could not fetch Gramps person {handle[:12]}: {exc}")
            counts["failed"] += 1
            continue

        gramps_name = person_display_name(person)
        changed = False
        for mr in person.get("media_list", []):
            rect = mr.get("rect")
            if not rect:
                continue  # plain person<->photo link, not a face crop
            lookup = by_handle.get(mr.get("ref"))
            if not lookup:
                counts["skipped"] += 1
                continue  # not Immich-sourced
            asset_id, media_obj = lookup
            if asset_id in manual:
                counts["skipped"] += 1
                continue

            matching = next(
                (f for f in await faces_for(asset_id)
                 if (f.get("person") or {}).get("id") == immich_pid),
                None,
            )
            if not matching:
                counts["skipped"] += 1
                continue

            new_rect = immich_face_to_gramps_rect(matching, pad_factor=FACE_PAD_FACTOR)
            if not new_rect or new_rect == list(rect):
                counts["unchanged"] += 1
                continue

            old_rect = list(rect)
            if apply:
                mr["rect"] = new_rect
                changed = True
            counts["updated"] += 1
            yield SyncEvent(
                kind="item", entity="face",
                action="updated" if apply else "would_update",
                source_id=asset_id,
                gramps_id=person.get("gramps_id"),
                title=f"{gramps_name} on '{media_obj.get('desc') or asset_id[:8]}'",
                data={"old_rect": old_rect, "rect": new_rect,
                      "media_gramps_id": media_obj.get("gramps_id")},
            )

        if changed:
            try:
                await gramps.update_person(handle, person)
            except Exception as exc:  # noqa: BLE001
                yield SyncEvent(kind="error", entity="face",
                                detail=f"save {gramps_name} failed: {exc}")
                counts["failed"] += 1

    yield SyncEvent(kind="summary", data=counts)


# ---------------------------------------------------------------------------
# Synced-media browser + manual-faces lock
# ---------------------------------------------------------------------------

async def synced_media_listing(
    gramps: GrampsClient, immich: ImmichClient, conn: sqlite3.Connection
) -> list[dict]:
    manual = await manual_face_asset_ids(immich)

    face_links_per_media: dict[str, list[dict]] = {}
    for entry in list_links(conn):
        handle = entry["gramps_handle"]
        try:
            person = await gramps.get_person(handle)
        except Exception as exc:  # noqa: BLE001
            log.warning("get_person %s failed: %s", handle[:12], exc)
            continue
        label = entry.get("label") or person_display_name(person)
        for mr in person.get("media_list", []):
            if mr.get("rect") and mr.get("ref"):
                face_links_per_media.setdefault(mr["ref"], []).append(
                    {"gramps_handle": handle, "label": label}
                )

    items = []
    for asset_id, m in (await synced_immich_media(gramps)).items():
        items.append({
            "media_handle": m["handle"],
            "gramps_id": m.get("gramps_id", ""),
            "title": m.get("desc") or asset_id[:8],
            "immich_asset_id": asset_id,
            "is_manual": asset_id in manual,
            "face_links": face_links_per_media.get(m["handle"], []),
        })
    items.sort(key=lambda r: r["title"].lower())
    return items


async def set_asset_lock(
    gramps: GrampsClient,
    immich: ImmichClient,
    conn: sqlite3.Connection,
    asset_id: str,
    locked: bool,
) -> dict:
    """Lock = tag Sync/ManualFaces + recompute tight rects for linked faces.
    Unlock = remove the tag (rects revert on the next re-pad run)."""
    tag_id = await immich.resolve_tag_id(MANUAL_FACES_TAG)
    if not tag_id:
        raise ValueError(f"{MANUAL_FACES_TAG} tag not found in Immich — create it first")

    if not locked:
        await immich.untag_assets(tag_id, [asset_id])
        return {"asset_id": asset_id, "is_manual": False}

    await immich.tag_assets(tag_id, [asset_id])

    media_obj = None
    for aid, m in (await synced_immich_media(gramps)).items():
        if aid == asset_id:
            media_obj = m
            break
    if media_obj is None:
        return {"asset_id": asset_id, "is_manual": True, "rects_updated": 0,
                "warning": "asset is not synced to Gramps; tag added but no rects to revert"}

    media_handle = media_obj["handle"]
    immich_to_handle = person_map_dict(conn)
    rects_updated = 0
    for face in await immich.get_faces(asset_id):
        immich_pid = (face.get("person") or {}).get("id")
        handle = immich_to_handle.get(immich_pid) if immich_pid else None
        if not handle:
            continue
        tight = immich_face_to_gramps_rect(face, pad_factor=0.0)
        if not tight:
            continue
        try:
            person = await gramps.get_person(handle)
        except Exception as exc:  # noqa: BLE001
            log.warning("Could not fetch Gramps person %s: %s", handle[:12], exc)
            continue
        changed = False
        for mr in person.get("media_list", []):
            if mr.get("ref") == media_handle and mr.get("rect") and mr["rect"] != tight:
                mr["rect"] = tight
                changed = True
        if changed:
            await gramps.update_person(handle, person)
            rects_updated += 1

    return {"asset_id": asset_id, "is_manual": True, "rects_updated": rects_updated}
